<?php
spl_autoload_register(function ($class) {
    $baseDir = dirname(__DIR__) . '/';
    $prefixes = [
        'Core\\' => 'core/',
        'App\\' => 'src/'
    ];
    foreach ($prefixes as $prefix => $dir) {
        $len = strlen($prefix);
        if (strncmp($prefix, $class, $len) !== 0) {
            continue;
        }
        $relativeClass = substr($class, $len);
        $file = $baseDir . $dir . str_replace('\\', '/', $relativeClass) . '.php';
        if (file_exists($file)) {
            require $file;
            return;
        }
    }
});

use Core\Application;

$app = new Application();
$db = $app->db;

echo "Wiping existing data...\n";
$db->query("SET FOREIGN_KEY_CHECKS = 0;");
$db->query("TRUNCATE TABLE categories;");
$db->query("TRUNCATE TABLE products;");
$db->query("TRUNCATE TABLE product_variants;");
$db->query("TRUNCATE TABLE product_images;");
$db->query("SET FOREIGN_KEY_CHECKS = 1;");
echo "Data wiped.\n";

echo "Inserting categories...\n";
$categories = [
    [1, 'Bandhej Sarees', 'bandhej-sarees'],
    [2, 'Banarasi Sarees', 'banarasi-sarees'],
    [3, 'Gotta Patti Chunri Sarees', 'gotta-patti-sarees'],
    [4, 'Pittan Work Sarees', 'pittan-work-sarees'],
    [5, 'Printed Sarees', 'printed-sarees'],
    [6, 'Pyor Gotta Patti Sarees', 'pyor-gotta-patti-sarees']
];

$stmtCat = $db->prepare("INSERT INTO categories (id, name, slug) VALUES (?, ?, ?)");
foreach ($categories as $c) {
    $stmtCat->execute($c);
}

echo "Categories inserted.\n";

$sqlProducts = <<<SQL
INSERT INTO `products` (`category_id`, `name`, `description`, `slug`, `price`, `photo`, `date_view`, `counter`) VALUES
(1, 'Royal Blue Bandhej Saree', 'A vibrant royal blue Bandhej saree with intricate white tie-dye patterns and a unique pallu featuring broad gold and dark blue stripes.', 'royal-blue-bandhej-saree', 4000.00, 'Bandhej (1).jpg', CURDATE(), 0),
(1, 'Navy Blue and White Bandhej Saree', 'A striking navy blue Bandhej saree with a large, intricate white and light blue circular pattern on the pallu and a bold gold striped border.', 'navy-blue-white-bandhej-saree', 4500.00, 'Bandhej (2).jpg', CURDATE(), 0),
(1, 'Teal Bandhej Saree', 'A rich teal Bandhej saree featuring small yellow dot patterns and a golden pallu with detailed motifs of human figures.', 'teal-bandhej-saree', 4200.00, 'Bandhej (3).jpg', CURDATE(), 0),
(1, 'Light Purple Bandhej Saree', 'A delicate light purple Bandhej saree with subtle white tie-dye dots and a wide, elegant golden border on the pallu.', 'light-purple-bandhej-saree', 3800.00, 'Bandhej (4).jpg', CURDATE(), 0),
(1, 'Red and Rainbow Bandhej Saree', 'A striking Bandhej saree with a red top half and a vibrant rainbow-striped bottom half, finished with a classic red and gold border.', 'red-rainbow-bandhej-saree', 5000.00, 'Bandhej (5).jpg', CURDATE(), 0),
(1, 'Classic Red Bandhej Saree', 'A traditional red Bandhej saree adorned with small white and yellow tie-dye dot patterns and a pallu featuring intricate white paisley designs and a golden border.', 'classic-red-bandhej-saree', 4100.00, 'Bandhej (6).jpg', CURDATE(), 0),
(1, 'Rainbow and Red Bandhej Saree', 'A vibrant Bandhej saree featuring a red top portion and a multi-colored rainbow-striped design, leading to a traditional red and gold woven border.', 'rainbow-red-bandhej-saree', 5000.00, 'Bandhej (7).jpg', CURDATE(), 0),
(1, 'Purple Geometric Bandhej Saree', 'A sophisticated purple Bandhej saree with complex geometric patterns in white and orange, complemented by an ornate golden border.', 'purple-geometric-bandhej-saree', 4800.00, 'Bandhej (8).jpg', CURDATE(), 0),
(1, 'Green Bandhej Saree', 'A bright green Bandhej saree with all-over intricate white and yellow patterns forming floral and geometric shapes.', 'green-bandhej-saree', 4300.00, 'Bandhej (9).jpg', CURDATE(), 0),
(1, 'Coral Red Bandhej Saree', 'A beautiful coral red Bandhej saree with subtle white and orange tie-dye dots arranged in floral and diamond-shaped motifs across the fabric.', 'coral-red-bandhej-saree', 4100.00, 'Bandhej (10).jpg', CURDATE(), 0),
(1, 'Red and Pink Diamond Bandhej Saree', 'A vibrant Bandhej saree in a red and pink color combination, featuring distinct diamond-shaped patterns with intricate floral and dot motifs.', 'red-pink-diamond-bandhej-saree', 5200.00, 'Bandhej (11).jpg', CURDATE(), 0),
(1, 'Hot Pink and Red Bandhej Saree', 'A stunning hot pink Bandhej saree with prominent red and orange diamond patterns, each with a detailed floral center.', 'hot-pink-red-bandhej-saree', 5100.00, 'Bandhej (12).jpg', CURDATE(), 0),
(1, 'Hot Pink Circle Bandhej Saree', 'This hot pink Bandhej saree features two large, prominent circular patterns created from fine white tie-dye dots, giving it a classic and delicate look.', 'hot-pink-circle-bandhej-saree', 4900.00, 'Bandhej (18).jpg', CURDATE(), 0),
(1, 'Green Circle Bandhej Saree', 'A bright green Bandhej saree with two prominent circular patterns created from fine white tie-dye dots, complemented by scattered dots across the fabric.', 'green-circle-bandhej-saree', 5000.00, 'Bandhej (19).jpg', CURDATE(), 0),
(1, 'Red and Orange Bandhej Saree', 'A vibrant red Bandhej saree with two large circular patterns that transition from orange to yellow and a deep red center, and fine wave-like patterns.', 'red-orange-bandhej-saree', 5300.00, 'Bandhej (20).jpg', CURDATE(), 0),
(1, 'Red and Hot Pink Circle Bandhej Saree', 'This vibrant red Bandhej saree features two large, circular designs in a bold hot pink with finely detailed concentric patterns.', 'red-hot-pink-circle-bandhej-saree', 5200.00, 'Bandhej (21).jpg', CURDATE(), 0),
(1, 'Red, Pink, and Gold Brocade Saree', 'A luxurious Bandhej saree that transitions from deep red to hot pink, adorned with a heavy gold woven brocade pattern and a broad, intricate gold border.', 'red-pink-gold-brocade-saree', 6500.00, 'Bandhej (23).jpg', CURDATE(), 0),
(1, 'Green and Gold Brocade Saree', 'An elegant dark green Bandhej saree with a rich, all-over gold woven brocade pattern featuring large paisley and geometric motifs, and a wide, detailed border.', 'green-gold-brocade-saree', 6800.00, 'Bandhej (24).jpg', CURDATE(), 0),
(1, 'Blue, Green, and Gold Brocade Saree', 'A stunning saree that fades from royal blue to teal green, featuring an elaborate gold woven brocade pattern of floral and geometric shapes with a wide, decorative border.', 'blue-green-gold-brocade-saree', 6700.00, 'Bandhej (26).jpg', CURDATE(), 0),
(1, 'Magenta and Gold Brocade Saree', 'A rich magenta and hot pink Bandhej saree with a broad, ornate gold woven border and an all-over intricate gold pattern, reminiscent of a Banarasi weave.', 'magenta-gold-brocade-saree', 6600.00, 'Bandhej (27).jpg', CURDATE(), 0),
(1, 'Royal Blue and Gold Brocade Saree', 'An elegant royal blue saree with an all-over heavy gold brocade pattern, including large paisley-like motifs and a diamond pattern, and a wide, intricate gold border.', 'royal-blue-gold-brocade-saree', 7200.00, 'Bandhej (28).jpg', CURDATE(), 0),
(1, 'Pink, Green, and Gold Brocade Saree', 'A multi-colored saree that transitions from magenta and pink to green and gold, covered in a heavy gold brocade pattern featuring intricate leaf and floral motifs.', 'pink-green-gold-brocade-saree', 7300.00, 'Bandhej (30).jpg', CURDATE(), 0),
(1, 'Red and Gold Banarasi-style Saree', 'A traditional red saree with a lush gold woven pattern that combines large oval motifs with smaller floral patterns, and a wide, intricate gold border.', 'red-gold-banarasi-style-saree', 7000.00, 'Bandhej (31).jpg', CURDATE(), 0),
(1, 'Red and Gold Brocade Saree', 'This stunning red saree is adorned with a rich, all-over gold brocade pattern, featuring a mix of a large, intricate diamond pattern and a detailed leaf motif, with a heavy, ornate gold border.', 'red-gold-brocade-saree', 7100.00, 'Bandhej (33).jpg', CURDATE(), 0),
(1, 'Teal Bandhej Saree', 'A beautiful teal Bandhej saree with an all-over fine white dot pattern and a pallu highlighted by a wide, striking gold border.', 'teal-bandhej-saree', 4500.00, 'Bandhej (35).jpg', CURDATE(), 0),
(1, 'Golden Yellow Bandhej Saree', 'A bright golden yellow Bandhej saree with small white dot patterns, and a wide, shimmery gold border on the pallu.', 'golden-yellow-bandhej-saree', 4400.00, 'Bandhej (36).jpg', CURDATE(), 0),
(1, 'Pink Saree', 'Bandhej', 'pink-bandhej', 3900.00, 'Bandhej (37).jpg', CURDATE(), 0),
(1, 'Emerald Saree', 'Bandhej', 'emerald-bandhej', 3900.00, 'Bandhej (38).jpg', CURDATE(), 0),
(1, 'Mocha Saree', 'Bandhej', 'mocha-bandhej', 3900.00, 'Bandhej (39).jpg', CURDATE(), 0),
(1, 'Cobalt Saree', 'Bandhej', 'cobalt-bandhej', 3900.00, 'Bandhej (40).jpg', CURDATE(), 0),
(1, 'Mahogany Saree', 'Bandhej', 'mahogany-bandhej', 3900.00, 'Bandhej (41).jpg', CURDATE(), 0),
(1, 'Slate Saree', 'Bandhej', 'slate-bandhej', 3900.00, 'Bandhej (42).jpg', CURDATE(), 0),
(1, 'Indigo Saree', 'Bandhej', 'indigo-bandhej', 3900.00, 'Bandhej (43).jpg', CURDATE(), 0),
(1, 'Lilac Saree', 'Bandhej', 'lilac-bandhej', 3900.00, 'Bandhej (44).jpg', CURDATE(), 0),
(1, 'Golden-Pink-Red Gotta Patti Bandhej', 'Oval and floral gold zari design', 'golden-pink-red-zari', 5700.00, 'gotta patti Bandhej (1).jpg', CURDATE(), 0),
(1, 'Golden-Pink-Red Gotta Patti Bandhej', 'Oval and floral gold zari design', 'golden-pink-red-zari-alt', 5700.00, 'gotta patti Bandhej (2).jpg', CURDATE(), 0),
(1, 'Gotta Patti Bandhej Saree', 'Beautiful pink Bandhej saree with intricate gotta patti embroidery and golden border.', 'gotta-patti-bandhej-1', 5500.00, 'gotta patti Bandhej (3).jpg', CURDATE(), 0),
(1, 'Gotta Patti Bandhej Saree', 'Elegant pink Bandhej saree with golden zari border and traditional patterns.', 'gotta-patti-bandhej-2', 5600.00, 'gotta patti Bandhej (4).jpg', CURDATE(), 0),
(1, 'Gotta Patti Bandhej Saree', 'Red Bandhej saree with heavy gotta patti work and golden finishing.', 'gotta-patti-bandhej-3', 5800.00, 'gotta patti Bandhej (5).jpg', CURDATE(), 0),
(1, 'Gotta Patti Bandhej Saree', 'Royal red Bandhej saree with floral gotta patti embroidery and zari border.', 'gotta-patti-bandhej-4', 6000.00, 'gotta patti Bandhej (6).jpg', CURDATE(), 0),
(1, 'Gotta Patti Bandhej Saree', 'Classic pink Bandhej saree with heavy border work and golden detailing.', 'gotta-patti-bandhej-5', 5700.00, 'gotta patti Bandhej (7).jpg', CURDATE(), 0),
(1, 'Gotta Patti Bandhej Saree', 'Pink Bandhej saree featuring traditional diamond patterns and gotta patti finish.', 'gotta-patti-bandhej-6', 5600.00, 'gotta patti Bandhej (8).jpg', CURDATE(), 0),
(1, 'Gotta Patti Bandhej Saree', 'Designer pink Bandhej saree with elephant and peacock motifs in gotta patti.', 'gotta-patti-bandhej-7', 6200.00, 'gotta patti Bandhej (9).jpg', CURDATE(), 0),
(1, 'Gotta Patti Bandhej Saree', 'Traditional Bandhej saree in magenta shade with heavy border work.', 'gotta-patti-bandhej-8', 5900.00, 'gotta patti Bandhej (10).jpg', CURDATE(), 0),
(1, 'Gotta Patti Bandhej Saree', 'Exclusive Bandhej saree with detailed floral gotta patti embroidery.', 'gotta-patti-bandhej-9', 6100.00, 'gotta patti Bandhej (11).jpg', CURDATE(), 0),
(3, 'Red Bandhej Chunri', 'Red Bandhej Chunri saree with intricate gotta patti border, floral motifs, and diamond-shaped Bandhej patterns.', 'gotta-patti-chunri-1', 4600.00, 'Gotta Patti Chunri (1).jpg', CURDATE(), 0),
(3, 'Red Bandhani Chunri', 'Traditional red bandhani saree with golden gotta patti border', 'red-bandhani-chunri', 4800, 'Gotta Patti Chunri (2).jpg', CURDATE(), 0),
(3, 'Magenta Bandhani Chunri', 'Elegant magenta bandhani saree with golden border', 'magenta-bandhani-chunri', 4800, 'Gotta Patti Chunri (3).jpg', CURDATE(), 0),
(3, 'Designer Bandhani Chunri', 'Handcrafted bandhani chunri with floral motifs and zari work', 'designer-bandhani-chunri', 4500, 'Gotta Patti Chunri (4).jpg', CURDATE(), 0),
(3, 'Multicolor Bandhani Chunri', 'Red saree with multicolor bandhani designs and gotta work', 'multicolor-bandhani-chunri', 4500, 'Gotta Patti Chunri (5).jpg', CURDATE(), 0),
(3, 'Classic Red Bandhani Chunri', 'Rich red bandhani saree with detailed golden border', 'classic-red-bandhani-chunri', 4800, 'Gotta Patti Chunri (6).jpg', CURDATE(), 0),
(3, 'Red Bandhani with Floral Work', 'Chunri with red base, white bandhani dots and floral gotta motifs', 'red-floral-bandhani-chunri', 5000, 'Gotta Patti Chunri (7).jpg', CURDATE(), 0),
(3, 'Velvet Style Bandhani Chunri', 'Luxurious velvet-look bandhani chunri with intricate gotta patti border', 'velvet-style-bandhani-chunri', 4900, 'Gotta Patti Chunri (8).jpg', CURDATE(), 0),
(3, 'Heavy Border Bandhani Chunri', 'Saree with heavy embroidery border and colorful motifs', 'heavy-border-bandhani-chunri', 6000, 'Gotta Patti Chunri (9).jpg', CURDATE(), 0),
(3, 'Dark Red Chunri - Intricate Silver Gota Patti', 'A stunning dark red chunri with a traditional bandhani pattern. The entire piece is richly adorned with intricate silver gota patti work, featuring elegant paisley and floral designs, perfect for weddings and special events.', 'dark-red-chunri-intricate-silver-gota-patti', 6200.00, 'Gotta Patti Chunri (12).jpg', CURDATE(), 0),
(3, 'Red Gotta Patti Chunri - Peacock Design', 'Traditional red Chunri with intricate Gotta Patti and Peacock motifs', 'red-gotta-patti-chunri-peacock', 4399.00, 'Gotta Patti Chunri (13).jpg', CURDATE(), 0),
(3, 'Red Gotta Patti Chunri - Floral Border', 'Elegant Chunri featuring golden floral border embroidery with bandhani style dots', 'red-gotta-patti-chunri-floral', 5599.00, 'Gotta Patti Chunri (14).jpg', CURDATE(), 0),
(3, 'Red Gotta Patti Chunri - Large Floral Pattern', 'Red Chunri with central floral embroidery and detailed border work', 'red-gotta-patti-chunri-large-floral', 4799.00, 'Gotta Patti Chunri (15).jpg', CURDATE(), 0),
(3, 'Red Gotta Patti Chunri - Full Embroidery Border', 'Heavy border embroidered Chunri with delicate Gotta Patti details', 'red-gotta-patti-chunri-heavy-border', 4799.00, 'Gotta Patti Chunri (16).jpg', CURDATE(), 0),
(3, 'Red Gotta Patti Chunri - Traditional Bandhani Style', 'Traditional bandhani style Chunri enhanced with golden Gotta Patti border', 'red-gotta-patti-chunri-bandhani', 3399.00, 'Gotta Patti Chunri (17).jpg', CURDATE(), 0),
(3, 'Red Gotta Patti Chunri - Golden Leaf Border', 'Red Chunri featuring golden leaf motifs and Gotta Patti embellishments', 'red-gotta-patti-chunri-leaf-border', 3599.00, 'Gotta Patti Chunri (18).jpg', CURDATE(), 0),
(3, 'Red Gotta Patti Chunri - Wedding Special', 'Special wedding Chunri with intricate Gotta Patti and peacock motifs', 'red-gotta-patti-chunri-wedding', 3999.00, 'Gotta Patti Chunri (19).jpg', CURDATE(), 0),
(3, 'Red Gotta Patti Chunri - Designer Border', 'Designer Chunri with diamond patterned embroidery and golden lace border', 'red-gotta-patti-chunri-designer', 3899.00, 'Gotta Patti Chunri (20).jpg', CURDATE(), 0),
(3, 'Red Gotta Patti Chunri - Royal Design', 'Royal style Chunri with detailed peacock, floral motifs and fine border work', 'red-gotta-patti-chunri-royal', 3399.00, 'Gotta Patti Chunri (21).jpg', CURDATE(), 0),
(3, 'Red Bandhani Chunri - Scalloped Silver Border', 'A vibrant red bandhani chunri featuring a beautiful silver gota patti border with a scalloped edge and delicate floral designs. The main fabric has a classic dotted pattern with an elegant central motif.', 'red-bandhani-chunri-scalloped-silver-border', 2650.00, 'Gotta Patti Chunri (22).jpg', CURDATE(), 0),
(3, 'Red Bandhani Chunri - Silver Floral and Paisley', 'A traditional red chunri with a series of wavy and intricate bandhani patterns across the body. The chunri is finished with a striking silver gotta patti border featuring paisley and floral designs.', 'red-bandhani-chunri-silver-floral-paisley', 2800.00, 'Gotta Patti Chunri (23).jpg', CURDATE(), 0),
(3, 'Deep Red Chunri - Sun Motif and Silver Border', 'A stunning chunri in a deep red shade, showcasing a detailed bandhani tie-and-dye pattern with large, bright sun-like motifs. It is embellished with a decorative silver gotta patti border.', 'deep-red-chunri-sun-motif-silver-border', 3450.00, 'Gotta Patti Chunri (24).jpg', CURDATE(), 0),
(3, 'Red and Orange Chunri - Wavy Silver Gota Work', 'An elegant chunri in red and orange with intricate wavy and paisley patterns in silver gotta patti. The border is finished with a detailed floral motif design, perfect for festive wear.', 'red-orange-chunri-wavy-silver-gota', 3050.00, 'Gotta Patti Chunri (25).jpg', CURDATE(), 0),
(3, 'Pinkish-Red Bandhani Chunri - Sunburst Gota Patti', 'A vibrant chunri in a beautiful mix of pink and red. This piece features a traditional dotted bandhani pattern with large, eye-catching sunburst motifs and a silver gotta patti border.', 'pinkish-red-bandhani-chunri-sunburst-gota-patti', 3500.00, 'Gotta Patti Chunri (26).jpg', CURDATE(), 0),
(3, 'Red Chunri - Detailed Silver Gota Patti Border', 'A classic red bandhani chunri that is heavily adorned with intricate silver gotta patti work. The detailed border features a scalloped edge and elaborate floral designs, adding a rich look to the piece.', 'red-chunri-detailed-silver-gota-patti-border', 4000.00, 'Gotta Patti Chunri (27).jpg', CURDATE(), 0),
(3, 'Red and Orange Chunri - Large Floral Motifs', 'This chunri combines a traditional red and orange bandhani pattern with large floral motifs scattered across the fabric. The border is a wide, intricate silver gotta patti design, creating a bold and beautiful statement.', 'red-orange-chunri-large-floral-motifs', 3300.00, 'Gotta Patti Chunri (28).jpg', CURDATE(), 0),
(3, 'Red Bandhani Chunri - Diamond and Circular Motifs', 'A traditional red bandhani chunri featuring a large diamond-shaped motif and several concentric circular patterns. The border is heavily embellished with silver gotta patti in a floral design, adding elegance to the piece.', 'red-bandhani-chunri-diamond-circular-motifs', 2600.00, 'Gotta Patti Chunri (29).jpg', CURDATE(), 0),
(3, 'Red Bandhani Chunri - Golden Wavy Gota Work', 'A rich red chunri with a traditional dotted bandhani pattern and a luxurious gold gotta patti border. The intricate design features wavy and circular patterns, giving it a classic and festive appeal.', 'red-bandhani-chunri-golden-wavy-gota', 3700.00, 'Gotta Patti Chunri (30).jpg', CURDATE(), 0),
(3, 'Red Chunri - Silver and Gold Gota Patti Border', 'A beautiful red chunri with a traditional bandhani pattern. It is uniquely embellished with both silver and gold gotta patti work, creating a dual-toned, rich border effect with wavy and paisley motifs.', 'red-chunri-silver-gold-gota-patti-border', 3300.00, 'Gotta Patti Chunri (31).jpg', CURDATE(), 0),
(3, 'Dark Red Chunri - Orange Sun Motifs', 'A dark red chunri with a beautiful bandhani pattern. It is decorated with large, vibrant orange sun-like motifs and a detailed silver gota patti border, giving it a rich and festive appearance.', 'dark-red-chunri-orange-sun-motifs', 2800.00, 'Gotta Patti Chunri (32).jpg', CURDATE(), 0),
(3, 'Maroon Chunri - Gold Gota Patti and Paisley', 'A stunning maroon chunri with a traditional bandhani pattern. The entire piece is richly adorned with intricate gold gota patti work, featuring elegant paisley and floral designs, perfect for weddings and special events.', 'maroon-chunri-gold-gota-patti-paisley', 4600.00, 'Gotta Patti Chunri (33).jpg', CURDATE(), 0),
(3, 'Maroon Chunri - Silver and Gold Gota Patti', 'A stunning maroon chunri with a traditional bandhani pattern. The entire piece is richly adorned with intricate silver and gold gota patti work, featuring elegant paisley and floral designs, perfect for special events.', 'maroon-chunri-silver-gold-gota-patti', 3250.00, 'Gotta Patti Chunri (34).jpg', CURDATE(), 0),
(3, 'Maroon Chunri - Wavy Silver Gota Patti', 'This maroon chunri features a traditional bandhani pattern with wavy and circular designs. The wide silver gota patti border, adorned with a floral and leaf pattern, adds a touch of sophistication.', 'maroon-chunri-wavy-silver-gota-patti', 4850.00, 'Gotta Patti Chunri (35).jpg', CURDATE(), 0),
(3, 'Dark Red Chunri - Large Sun Motifs', 'A dark red chunri with a traditional bandhani pattern. It is decorated with large, vibrant orange and silver sun-like motifs and a detailed silver gota patti border, giving it a rich and festive appearance.', 'dark-red-chunri-large-sun-motifs', 4300.00, 'Gotta Patti Chunri (36).jpg', CURDATE(), 0),
(3, 'Maroon Chunri - Leafy Silver Gota Patti', 'This elegant maroon chunri features a subtle bandhani pattern and is bordered with intricate silver gota patti work. The border showcases a beautiful leafy and floral design, perfect for adding a touch of grace to any outfit.', 'maroon-chunri-leafy-silver-gota-patti', 4900.00, 'Gotta Patti Chunri (37).jpg', CURDATE(), 0),
(3, 'Red and Orange Chunri - Circular Gota Patti', 'A folded red and orange chunri with intricate bandhani patterns in concentric circles and diamonds. The piece is bordered with a detailed silver gota patti design featuring floral motifs.', 'red-orange-chunri-circular-gota-patti', 2800.00, 'Gotta Patti Chunri (38).jpg', CURDATE(), 0),
(3, 'Maroon Bandhani Chunri - Floral Sun Motifs', 'This maroon chunri features a traditional dotted bandhani pattern with large, eye-catching floral-sun motifs. The border is finished with intricate silver gotta patti work, perfect for any festive occasion.', 'maroon-bandhani-chunri-floral-sun-motifs', 2950.00, 'Gotta Patti Chunri (39).jpg', CURDATE(), 0),
(3, 'Maroon Chunri - Silver Floral and Paisley', 'A traditional maroon chunri with a series of wavy and intricate bandhani patterns across the body. The chunri is finished with a striking silver gota patti border featuring paisley and floral designs.', 'maroon-chunri-silver-floral-paisley', 2850.00, 'Gotta Patti Chunri (40).jpg', CURDATE(), 0),
(3, 'Maroon Chunri - Leafy Border with Silver Gota Patti', 'This maroon chunri features an elegant bandhani pattern with scattered floral motifs. The border is a highlight, with intricate silver gota patti work showcasing a beautiful leafy and floral design.', 'maroon-chunri-leafy-border-silver-gota-patti', 4500.00, 'Gotta Patti Chunri (41).jpg', CURDATE(), 0),
(3, 'Folded Red Chunri - Gota Patti Sun and Floral', 'A folded red chunri showcasing a beautiful central sun motif and other floral designs in silver gota patti. The entire piece is bordered with intricate silver gota patti work, highlighting its craftsmanship.', 'folded-red-chunri-gota-patti-sun-floral', 2900.00, 'Gotta Patti Chunri (42).jpg', CURDATE(), 0),
(3, 'Red Silk Chunri - Gold Gota Patti and Checkered Pattern', 'A luxurious red silk chunri with a lustrous finish. The chunri features a unique checkered bandhani pattern and is bordered with a rich gold gota patti design, perfect for an opulent and traditional look.', 'red-silk-chunri-gold-gota-patti-checkered', 3500.00, 'Gotta Patti Chunri (43).jpg', CURDATE(), 0),
(3, 'Maroon Chunri - Pink and Silver Paisley', 'A maroon chunri with a traditional bandhani pattern and a detailed silver gota patti border. The border features a beautiful paisley design with subtle pink accents, adding a unique touch of color.', 'maroon-chunri-pink-silver-paisley', 3200.00, 'Gotta Patti Chunri (44).jpg', CURDATE(), 0),
(3, 'Red Chunri - Intricate Golden Gota Patti', 'A stunning red chunri with a grid-like pattern of golden gota patti. The border is heavily embellished with intricate golden embroidery and mirror work, giving the piece a rich and luxurious feel.', 'red-chunri-intricate-golden-gota-patti', 2800.00, 'Gotta Patti Chunri (45).jpg', CURDATE(), 0),
(3, 'Maroon Chunri - Leafy and Floral Gota Patti', 'This elegant maroon chunri features a subtle bandhani pattern and is bordered with intricate silver gota patti work. The border showcases a beautiful leafy and floral design with small, scattered motifs.', 'maroon-chunri-leafy-floral-gota-patti', 3700.00, 'Gotta Patti Chunri (46).jpg', CURDATE(), 0),
(3, 'Red Chunri - Large Circular Gota Patti Motif', 'A striking red chunri featuring a very large, intricate circular motif made of silver gota patti. The rest of the chunri has a classic bandhani pattern and a beautiful floral silver gota patti border.', 'red-chunri-large-circular-gota-patti-motif', 3100.00, 'Gotta Patti Chunri (47).jpg', CURDATE(), 0),
(3, 'Red and Orange Bandhani Chunri - Sunbursts', 'A vibrant chunri in red and orange, showcasing a traditional dotted bandhani pattern with large, bright sunburst motifs. It is finished with a decorative silver and gold gota patti border, perfect for festive occasions.', 'red-orange-bandhani-chunri-sunbursts', 4900.00, 'Gotta Patti Chunri (48).jpg', CURDATE(), 0),
(3, 'Maroon Chunri - Orange Sun Motifs with Silver Gota', 'A maroon chunri featuring a traditional bandhani dotted pattern and large orange sun-like motifs. It is finished with a wide and intricate silver gotta patti border, perfect for adding a touch of traditional elegance to any outfit.', 'maroon-chunri-orange-sun-motifs-silver-gota', 3100.00, 'Gotta Patti Chunri (49).jpg', CURDATE(), 0),
(3, 'Red Chunri - Golden Gota with Sunbursts', 'A luxurious red chunri with a smooth finish. This piece is a modern take on traditional design, featuring multiple lines of golden gota work with scattered sunburst motifs. The wide golden border adds to its grandeur.', 'red-chunri-golden-gota-sunbursts', 2500.00, 'Gotta Patti Chunri (50).jpg', CURDATE(), 0),
(4, 'Crimson Red Pittan Work Saree', 'A striking crimson red saree with classic Pittan work, making it an ideal choice for celebrations and traditional events.', 'crimson-red-pittan-work-saree', 3750.00, 'Pittan work (1).jpg', CURDATE(), 0),
(4, 'Pink Pittan Work Saree', 'Embrace a vibrant look with this beautiful pink saree, highlighted by exquisite Pittan work. The striking color combined with the detailed craftsmanship on the border and pallu offers a festive and celebratory feel.', 'pink-pittan-work-saree', 3750.00, 'Pittan work (2).jpg', CURDATE(), 0),
(4, 'Mauve Pittan Work Saree', 'A stunning Mauve saree adorned with delicate Pittan work. The soft color and shimmering gold embroidery create a regal look, ideal for evening events and formal gatherings where you want to make a sophisticated statement.', 'mauve-pittan-work-saree', 3750.00, 'Pittan work (3).jpg', CURDATE(), 0),
(4, 'Green Pittan Work Saree', 'This elegant green saree features intricate Pittan work, a traditional Rajasthani embroidery technique. The rich detailing on the border and scattered motifs on the body make it perfect for weddings, festivals, and other special occasions.', 'green-pittan-work-saree', 3750.00, 'Pittan work (4).jpg', CURDATE(), 0),
(4, 'Magenta Pittan Work Saree', 'A gorgeous magenta saree with intricate Pittan work, making it a bold and beautiful statement piece for any celebration.', 'magenta-pittan-work-saree', 3750.00, 'Pittan work (5).jpg', CURDATE(), 0),
(4, 'Plum Purple Pittan Work Saree', 'A royal plum purple saree featuring exquisite Pittan work along the borders, offering a sophisticated and elegant look.', 'plum-purple-pittan-work-saree', 3750.00, 'Pittan work (6).jpg', CURDATE(), 0),
(4, 'Fuchsia Pink Pittan Work Saree', 'A vibrant fuchsia saree adorned with detailed Pittan work on the borders and small motifs across the body, perfect for festive occasions.', 'fuchsia-pink-pittan-work-saree', 3750.00, 'Pittan work (7).jpg', CURDATE(), 0),
(4, 'Mustard Yellow Pittan Work Saree', 'A vibrant mustard yellow saree with contrasting silver Pittan work on the border and motifs, offering a bright and cheerful look.', 'mustard-yellow-pittan-work-saree', 3750.00, 'Pittan work (8).jpg', CURDATE(), 0),
(4, 'Dusty Rose Pittan Work Saree', 'This elegant saree in a dusty rose shade features a delicate self-woven floral pattern and a scalloped border with intricate Pittan work.', 'dusty-rose-pittan-work-saree', 3750.00, 'Pittan work (9).jpg', CURDATE(), 0),
(4, 'Dusty Rose Pittan Work Saree', 'This elegant saree features a self-woven floral pattern and a scalloped border with intricate Pittan work, creating a sophisticated and luxurious look.', 'dusty-rose-pittan-work-saree', 3750.00, 'Pittan work (10).jpg', CURDATE(), 0),
(4, 'Violet Crushed Pittan Work Saree', 'This unique violet saree features a crushed fabric texture with delicate gold Pittan motifs and a scalloped border, perfect for a contemporary festive style.', 'violet-crushed-pittan-work-saree', 3350.00, 'Pittan work (11).jpg', CURDATE(), 0),
(4, 'Aqua Blue Pittan Work Saree', 'This soothing aqua blue saree features a subtle self-woven pattern and is beautifully embellished with detailed Pittan work on the borders, perfect for a chic and elegant event.', 'aqua-blue-pittan-work-saree', 3750.00, 'Pittan work (12).jpg', CURDATE(), 0),
(4, 'Mint Green Pittan Work Saree', 'This serene mint green saree features a subtle self-woven pattern with shimmering Pittan work on the borders, creating a graceful and light festive outfit.', 'mint-green-pittan-work-saree', 3750.00, 'Pittan work (13).jpg', CURDATE(), 0),
(4, 'Dusty Rose Pittan Saree with Floral Pattern', 'This luxurious dusty rose saree combines a self-woven floral pattern with a beautiful scalloped border, meticulously handcrafted with Pittan work and small bead detailing.', 'dusty-rose-pittan-saree-floral-pattern', 3750.00, 'Pittan work (14).jpg', CURDATE(), 0),
(4, 'Mustard Yellow Pittan Saree with Scalloped Border', 'A vibrant mustard yellow saree featuring an intricately designed scalloped border with shimmering silver and pink Pittan work, perfect for adding a pop of color to any festive look.', 'mustard-yellow-pittan-saree-scalloped-border', 3750.00, 'Pittan work (15).jpg', CURDATE(), 0),
(4, 'Forest Green Pittan Saree with Scalloped Border', 'A rich forest green saree with a classic look, highlighted by a detailed scalloped border featuring a blend of silver and pink Pittan work and fine embroidery.', 'forest-green-pittan-saree-scalloped-border', 3750.00, 'Pittan work (16).jpg', CURDATE(), 0),
(4, 'Off-White Crushed Saree with Pittan Motifs', 'An elegant off-white saree with a stylish crushed texture, beautifully embellished with scattered golden Pittan motifs and a matching scalloped border for a sophisticated appearance.', 'off-white-crushed-saree-pittan-motifs', 3350.00, 'Pittan work (17).jpg', CURDATE(), 0),
(4, 'Dusty Blue Crushed Saree with Pittan Motifs', 'This elegant saree in a beautiful dusty blue shade features a crushed texture and is adorned with delicate Pittan motifs scattered across the body, finished with a simple scalloped border.', 'dusty-blue-crushed-saree-pittan-motifs', 3350.00, 'Pittan work (18).jpg', CURDATE(), 0),
(5, 'Navy Blue Paisley Printed Saree', 'A comfortable and stylish printed saree featuring a striking navy blue base with intricate red and white paisley and geometric patterns, ideal for daily wear or casual events.', 'navy-blue-paisley-printed-saree', 3750.00, 'Printed (1).jpg', CURDATE(), 0),
(5, 'Purple Paisley Printed Saree', 'A comfortable and stylish printed saree featuring a rich purple base with intricate pink and white paisley and geometric patterns, ideal for daily wear or casual events.', 'purple-paisley-printed-saree', 3750.00, 'Printed (2).jpg', CURDATE(), 0),
(5, 'Red Paisley Printed Saree', 'A comfortable and stylish printed saree featuring a vibrant red base with intricate black and white paisley and geometric patterns, ideal for daily wear or casual events.', 'red-paisley-printed-saree', 3750.00, 'Printed (3).jpg', CURDATE(), 0),
(5, 'Navy Blue Paisley Printed Saree', 'A comfortable and stylish printed saree featuring a striking navy blue base with intricate red and white paisley and geometric patterns, ideal for daily wear or casual events.', 'navy-blue-paisley-printed-saree', 3750.00, 'Printed (4).jpg', CURDATE(), 0),
(5, 'Pink Floral Motif Printed Saree', 'A rich pink saree with a delicate all-over floral motif and a heavy, ornate border, perfect for weddings and formal gatherings.', 'pink-floral-motif-printed-saree', 3050.00, 'Printed (5).jpg', CURDATE(), 0),
(5, 'Magenta Elephant and Geometric Printed Saree', 'A stunning magenta saree with a detailed elephant and geometric pattern on the pallu and body, perfect for special occasions and festive wear.', 'magenta-elephant-geometric-printed-saree', 3050.00, 'Printed (6).jpg', CURDATE(), 0),
(5, 'Purple Floral Bandhani Printed Saree', 'A purple saree with a traditional floral bandhani print, featuring a detailed border and a unique floral design on the pallu, suitable for traditional events.', 'purple-floral-bandhani-printed-saree', 3050.00, 'Printed (7).jpg', CURDATE(), 0),
(5, 'Red Geometric Floral Printed Saree', 'A vibrant red saree with a detailed geometric and floral print, featuring a striking floral border, ideal for festive events and celebrations.', 'red-geometric-floral-printed-saree', 3050.00, 'Printed (8).jpg', CURDATE(), 0),
(5, 'Pink Geometric Floral Printed Saree', 'A vibrant pink saree with a detailed geometric and floral print, featuring a striking floral border, ideal for festive events and celebrations.', 'pink-geometric-floral-printed-saree', 3050.00, 'Printed (9).jpg', CURDATE(), 0),
(5, 'Purple Floral Motif Printed Saree', 'A rich purple saree with a delicate all-over floral motif and a heavy, ornate border, perfect for weddings and formal gatherings.', 'purple-floral-motif-printed-saree', 3050.00, 'Printed (10).jpg', CURDATE(), 0),
(5, 'Purple Elephant and Geometric Printed Saree', 'A stunning purple saree with a detailed elephant and geometric pattern on the pallu and body, perfect for special occasions and festive wear.', 'purple-elephant-geometric-printed-saree', 3050.00, 'Printed (11).jpg', CURDATE(), 0),
(5, 'Purple Geometric Floral Printed Saree', 'A vibrant purple saree with a detailed geometric and floral print, featuring a striking floral border, ideal for festive events and celebrations.', 'purple-geometric-floral-printed-saree', 3050.00, 'Printed (12).jpg', CURDATE(), 0),
(5, 'Magenta Floral Bandhani Printed Saree', 'A magenta saree with a traditional floral bandhani print, featuring a detailed border and a unique floral design on the pallu, suitable for traditional events.', 'magenta-floral-bandhani-printed-saree', 3050.00, 'Printed (13).jpg', CURDATE(), 0),
(5, 'Pink Floral Bandhani Printed Saree', 'A pink saree with a traditional floral bandhani print, featuring a detailed border and a unique floral design on the pallu, suitable for traditional events.', 'pink-floral-bandhani-printed-saree', 3050.00, 'Printed (14).jpg', CURDATE(), 0),
(5, 'Pink Elephant and Geometric Printed Saree', 'A stunning pink saree with a detailed elephant and geometric pattern on the pallu and body, perfect for special occasions and festive wear.', 'pink-elephant-geometric-printed-saree', 3050.00, 'Printed (15).jpg', CURDATE(), 0),
(5, 'Yellow Elephant and Geometric Printed Saree', 'A stunning yellow saree with a detailed elephant and geometric pattern on the pallu and body, perfect for special occasions and festive wear.', 'yellow-elephant-geometric-printed-saree', 3050.00, 'Printed (16).jpg', CURDATE(), 0),
(5, 'Pink Floral Motif Printed Saree', 'A vibrant pink saree featuring large, intricate floral motifs, perfect for a chic and traditional look.', 'pink-floral-motif-printed-saree', 3050.00, 'Printed (17).jpg', CURDATE(), 0),
(5, 'Dark Purple Elephant and Geometric Printed Saree', 'A stunning dark purple saree with a detailed elephant and geometric pattern on the pallu and body, perfect for special occasions and festive wear.', 'dark-purple-elephant-geometric-printed-saree', 3050.00, 'Printed (18).jpg', CURDATE(), 0),
(5, 'Purple Floral Bandhani Printed Saree', 'A purple saree with a traditional floral bandhani print, featuring a detailed border and a unique floral design on the pallu, suitable for traditional events.', 'purple-floral-bandhani-printed-saree', 3050.00, 'Printed (19).jpg', CURDATE(), 0),
(5, 'Red Elephant and Geometric Saree', 'A stunning red saree with a detailed elephant and geometric pattern on the pallu and body, perfect for special occasions and festive wear.', 'red-elephant-and-geometric-saree', 3050.00, 'Printed (20).jpg', CURDATE(), 0),
(5, 'Magenta Floral Bandhani Saree', 'A magenta saree with a traditional floral bandhani print, featuring a detailed border and a unique floral design on the pallu, suitable for traditional events.', 'magenta-floral-bandhani-saree', 3050.00, 'Printed (21).jpg', CURDATE(), 0),
(5, 'Purple Floral Motif Saree', 'A rich purple saree with a delicate all-over floral motif and a heavy, ornate border, perfect for weddings and formal gatherings.', 'purple-floral-motif-saree', 3050.00, 'Printed (22).jpg', CURDATE(), 0),
(5, 'Pink Floral Motif Saree', 'A rich pink saree with a delicate all-over floral motif and a heavy, ornate border, perfect for weddings and formal gatherings.', 'pink-floral-motif-saree', 3050.00, 'Printed (23).jpg', CURDATE(), 0),
(5, 'Pink Geometric and Floral Saree', 'A vibrant pink saree with a detailed geometric and floral print, featuring a striking floral border, ideal for festive events and celebrations.', 'pink-geometric-and-floral-saree', 3050.00, 'Printed (24).jpg', CURDATE(), 0),
(5, 'Red Geometric and Floral Saree', 'A vibrant red saree with a detailed geometric and floral print, featuring a striking floral border, ideal for festive events and celebrations.', 'red-geometric-and-floral-saree', 3050.00, 'Printed (25).jpg', CURDATE(), 0),
(5, 'Dark Purple Floral Bandhani Saree', 'A dark purple saree with a traditional floral bandhani print, featuring a detailed border and a unique floral design on the pallu, suitable for traditional events.', 'dark-purple-floral-bandhani-saree', 3050.00, 'Printed (26).jpg', CURDATE(), 0),
(5, 'Maroon Floral Motif Saree', 'A rich maroon saree with a delicate all-over floral motif and a heavy, ornate border, perfect for weddings and formal gatherings.', 'maroon-floral-motif-saree', 3050.00, 'Printed (27).jpg', CURDATE(), 0),
(5, 'Yellow Geometric and Floral Saree', 'A vibrant yellow saree with a detailed geometric and floral print, featuring a striking floral border, ideal for festive events and celebrations.', 'yellow-geometric-and-floral-saree', 3050.00, 'Printed (28).jpg', CURDATE(), 0),
(5, 'Red Floral Motif Saree', 'A rich red saree with a delicate all-over floral motif and a heavy, ornate border, perfect for weddings and formal gatherings.', 'red-floral-motif-saree', 3050.00, 'Printed (29).jpg', CURDATE(), 0),
(5, 'Red Geometric Printed Saree', 'A rich red saree with a geometric bandhani print and a heavy, ornate circle pattern on the pallu, perfect for weddings and formal gatherings.', 'red-geometric-printed-saree', 3050.00, 'Printed (30).jpg', CURDATE(), 0),
(5, 'Red Floral Bandhani Saree', 'A red saree with a traditional floral bandhani print, featuring a detailed border and a unique floral design on the pallu, suitable for traditional events.', 'red-floral-bandhani-saree', 3050.00, 'Printed (31).jpg', CURDATE(), 0),
(5, 'Purple Geometric and Floral Saree', 'A vibrant purple saree with a detailed geometric and floral print, featuring a striking floral border, ideal for festive events and celebrations.', 'purple-geometric-and-floral-saree', 3050.00, 'Printed (32).jpg', CURDATE(), 0),
(5, 'Magenta Floral Bandhani Saree', 'A magenta saree with a traditional floral bandhani print, featuring a detailed border and a unique floral design on the pallu, suitable for traditional events.', 'magenta-floral-bandhani-saree', 3050.00, 'Printed (33).jpg', CURDATE(), 0),
(5, 'Orange Elephant and Circle Print Saree', 'A stunning orange saree with a detailed elephant and geometric pattern on the pallu and an intricate circle design on the body, perfect for special occasions.', 'orange-elephant-and-circle-print-saree', 3050.00, 'Printed (34).jpg', CURDATE(), 0),
(5, 'Yellow Elephant and Geometric Print Saree', 'A stunning yellow saree with a detailed elephant and geometric pattern on the pallu and an intricate circle design on the body, perfect for special occasions.', 'yellow-elephant-and-geometric-print-saree', 3050.00, 'Printed (35).jpg', CURDATE(), 0),
(5, 'Red Bird and Geometric Print Saree', 'A vibrant red saree featuring a unique checked and bird pattern on the pallu and a delicate geometric print on the body, perfect for special occasions.', 'red-bird-and-geometric-print-saree', 3050.00, 'Printed (36).jpg', CURDATE(), 0),
(5, 'Purple Geometric and Striped Saree', 'A rich purple saree featuring a bold geometric and striped design on the pallu and an intricate check pattern on the body, perfect for a traditional and stylish look.', 'purple-geometric-and-striped-saree', 3050.00, 'Printed (37).jpg', CURDATE(), 0),
(5, 'Pink Geometric Bandhani Saree', 'A stunning pink saree with a geometric bandhani print and a heavy, ornate circle and mirror work border, perfect for weddings and formal gatherings.', 'pink-geometric-bandhani-saree', 3050.00, 'Printed (38).jpg', CURDATE(), 0),
(5, 'Purple Geometric Bandhani Saree', 'A stunning purple saree with a geometric bandhani print and a heavy, ornate circle and mirror work border, perfect for weddings and formal gatherings.', 'purple-geometric-bandhani-saree', 3050.00, 'Printed (39).jpg', CURDATE(), 0),
(5, 'Orange Geometric Bandhani Saree', 'A stunning orange saree with a geometric bandhani print and a heavy, ornate circle and mirror work border, perfect for weddings and formal gatherings.', 'orange-geometric-bandhani-saree', 3050.00, 'Printed (40).jpg', CURDATE(), 0),
(5, 'Purple Elephant and Geometric Print Saree', 'A stunning purple saree with a detailed elephant and geometric pattern on the pallu and an intricate circle design on the body, perfect for special occasions.', 'purple-elephant-and-geometric-print-saree', 3050.00, 'Printed (41).jpg', CURDATE(), 0),
(5, 'Red Geometric Bandhani Saree', 'A stunning red saree with a geometric bandhani print and a heavy, ornate circle and mirror work border, perfect for weddings and formal gatherings.', 'red-geometric-bandhani-saree', 3050.00, 'Printed (42).jpg', CURDATE(), 0),
(5, 'Red Wedding Motif Saree', 'A traditional red saree with intricate wedding motifs and a detailed geometric print, featuring a heavy golden border, ideal for bridal wear.', 'red-wedding-motif-saree', 3050.00, 'Printed (43).jpg', CURDATE(), 0),
(5, 'Yellow Bird and Geometric Print Saree', 'A vibrant yellow saree featuring a unique checked and bird pattern on the pallu and a delicate geometric print on the body, perfect for special occasions.', 'yellow-bird-and-geometric-print-saree', 3050.00, 'Printed (44).jpg', CURDATE(), 0),
(5, 'Red Elephant and Circle Print Saree', 'A stunning red saree with a detailed elephant and geometric pattern on the pallu and an intricate circle design on the body, perfect for special occasions.', 'red-elephant-and-circle-print-saree', 3050.00, 'Printed (45).jpg', CURDATE(), 0),
(5, 'Lavender Wedding Motif Saree', 'A traditional lavender saree with intricate wedding motifs and a detailed geometric print, featuring a heavy golden border, ideal for bridal wear.', 'lavender-wedding-motif-saree', 3050.00, 'Printed (46).jpg', CURDATE(), 0),
(5, 'Green Geometric Bandhani Saree', 'A stunning green saree with a geometric bandhani print and a heavy, ornate circle and mirror work border, perfect for weddings and formal gatherings.', 'green-geometric-bandhani-saree', 3050.00, 'Printed (47).jpg', CURDATE(), 0),
(5, 'Maroon Bird and Geometric Print Saree', 'A vibrant maroon saree featuring a unique checked and bird pattern on the pallu and a delicate geometric print on the body, perfect for special occasions.', 'maroon-bird-and-geometric-print-saree', 3050.00, 'Printed (48).jpg', CURDATE(), 0),
(5, 'Purple Bird and Geometric Print Saree', 'A vibrant purple saree featuring a unique checked and bird pattern on the pallu and a delicate geometric print on the body, perfect for special occasions.', 'purple-bird-and-geometric-print-saree', 3050.00, 'Printed (49).jpg', CURDATE(), 0),
(5, 'Green Geometric Bandhani Saree', 'A stunning green saree with a geometric bandhani print and a heavy, ornate circle and mirror work border, perfect for weddings and formal gatherings.', 'green-geometric-bandhani-saree', 3050.00, 'Printed (50).jpg', CURDATE(), 0),
(5, 'Maroon Bird and Geometric Print Saree', 'A vibrant maroon saree featuring a unique checked and bird pattern on the pallu and a delicate geometric print on the body, perfect for special occasions.', 'maroon-bird-and-geometric-print-saree', 3050.00, 'Printed (51).jpg', CURDATE(), 0),
(5, 'Purple Elephant and Circle Print Saree', 'A stunning purple saree with a detailed elephant and geometric pattern on the pallu and an intricate circle design on the body, perfect for special occasions.', 'purple-elephant-and-circle-print-saree', 3050.00, 'Printed (52).jpg', CURDATE(), 0),
(5, 'Dark Purple Geometric Bandhani Saree', 'A stunning dark purple saree with a geometric bandhani print and a heavy, ornate circle and mirror work border, perfect for weddings and formal gatherings.', 'dark-purple-geometric-bandhani-saree', 3050.00, 'Printed (53).jpg', CURDATE(), 0),
(5, 'Purple Wedding Motif Saree', 'A traditional purple saree with intricate wedding motifs and a detailed geometric print, featuring a heavy golden border, ideal for bridal wear.', 'purple-wedding-motif-saree', 3050.00, 'Printed (54).jpg', CURDATE(), 0),
(5, 'Yellow Geometric Bandhani Saree', 'A stunning yellow saree with a geometric bandhani print and a heavy, ornate circle and mirror work border, perfect for weddings and formal gatherings.', 'yellow-geometric-bandhani-saree', 3050.00, 'Printed (55).jpg', CURDATE(), 0),
(5, 'Lavender Wedding Motif Saree', 'A traditional lavender saree with intricate wedding motifs and a detailed geometric print, featuring a heavy golden border, ideal for bridal wear.', 'lavender-wedding-motif-saree', 3050.00, 'Printed (56).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A stunning saree featuring intricate Gota Patti work on a silk fabric. The saree has a beautiful border with floral motifs and a delicate single flower on the pallu.', 'pyor-gotta-patti-saree', 2950, 'Pyor Gotta Patti (1).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A stunning magenta saree featuring intricate Gota Patti work on a silk fabric. The saree has a beautiful border with a zigzag pattern and scattered star motifs on the body.', 'pyor-gotta-patti-saree', 2950, 'Pyor Gotta Patti (2).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A stunning rust-colored saree with fine silver Gota Patti work. The saree has a unique geometric and floral border and delicate scattered motifs on the body.', 'pyor-gotta-patti-saree-rust', 3200, 'Pyor Gotta Patti (3).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A stunning dusty rose saree featuring intricate Gota Patti work on a pure silk fabric. The saree has a beautiful border with floral and leaf motifs and delicate leaf motifs scattered on the body.', 'pyor-gotta-patti-saree-dusty-rose', 3150, 'Pyor Gotta Patti (4).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A gorgeous pink saree with golden Gota Patti work. The border features a beautiful floral pattern, complemented by small floral motifs scattered across the fabric.', 'pyor-gotta-patti-saree-pink', 2950, 'Pyor Gotta Patti (5).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'An elegant dark green saree with Gota Patti work. The border showcases a delicate floral design, and the body is adorned with small scattered star motifs.', 'pyor-gotta-patti-saree-dark-green', 2950, 'Pyor Gotta Patti (6).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A lovely olive green saree with intricate Gota Patti work. The saree has a classic floral and zigzag border, with tiny star motifs scattered on the body.', 'pyor-gotta-patti-saree-olive-green', 2950, 'Pyor Gotta Patti (7).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A beautiful purple saree with fine Gota Patti work. The saree features a border with zigzag and floral patterns, with small star motifs scattered throughout the fabric.', 'pyor-gotta-patti-saree-purple', 2950, 'Pyor Gotta Patti (8).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A stunning red saree with classic Gota Patti work. The saree features a zigzag and floral patterned border and is decorated with small, scattered star motifs.', 'pyor-gotta-patti-saree-red', 3150, 'Pyor Gotta Patti (9).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A radiant fuchsia saree featuring delicate Gota Patti work on pure silk. The border has a mix of zigzag and floral patterns, with small flower motifs scattered across the body.', 'pyor-gotta-patti-saree-fuchsia', 3150, 'Pyor Gotta Patti (10).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A striking magenta saree adorned with intricate silver Gota Patti work. The border showcases a charming combination of floral and zigzag designs, with small floral motifs scattered on the body.', 'pyor-gotta-patti-saree-magenta', 2950, 'Pyor Gotta Patti (11).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'An elegant purple saree with fine golden Gota Patti work. The border features a zigzag and floral pattern, with delicate leaf motifs scattered throughout the fabric.', 'pyor-gotta-patti-saree-purple-2', 2950, 'Pyor Gotta Patti (12).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A gorgeous blue-green saree with heavy Gota Patti work. The border is designed with large spiral and zigzag patterns, with small floral motifs scattered on the brocade fabric.', 'pyor-gotta-patti-saree-blue-green-brocade', 3800, 'Pyor Gotta Patti (13).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A sophisticated beige saree with Gota Patti work on a brocade pattern. The saree has a stunning border with floral and zigzag motifs, with scattered floral designs on the body.', 'pyor-gotta-patti-saree-beige-brocade', 3200, 'Pyor Gotta Patti (14).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A beautiful pista green saree with intricate Gota Patti work on a brocade pattern. The border features a zigzag pattern with floral motifs, with scattered star motifs on the body.', 'pyor-gotta-patti-saree-pista-green-brocade', 2950, 'Pyor Gotta Patti (15).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A stunning pista green saree with Gota Patti work on a brocade pattern. The saree has a bold Gota Patti border with unique floral motifs and scattered leaf designs on the body.', 'pyor-gotta-patti-saree-pista-green', 3200, 'Pyor Gotta Patti (16).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'An elegant pink saree with intricate Gota Patti work on a brocade pattern. The saree features a detailed floral and zigzag border with beautiful square floral patterns and scattered motifs on the body.', 'pyor-gotta-patti-saree-pink-brocade', 3500, 'Pyor Gotta Patti (17).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A sophisticated dusty grey saree featuring intricate Gota Patti work on a brocade pattern. The border has a scalloped floral design, with small floral motifs scattered throughout the fabric.', 'pyor-gotta-patti-saree-dusty-grey', 3200, 'Pyor Gotta Patti (18).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A beautiful pista green saree featuring intricate Gota Patti work on a brocade pattern. The border is a unique zigzag and floral design, with delicate motifs scattered on the body.', 'pyor-gotta-patti-saree-pista-green-2', 3200, 'Pyor Gotta Patti (19).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A graceful dusty pink saree with fine Gota Patti work on a brocade pattern. The border showcases an elegant scroll and floral design with scattered small motifs on the body.', 'pyor-gotta-patti-saree-dusty-pink', 3200, 'Pyor Gotta Patti (20).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A luxurious wine-colored saree with rich Gota Patti work. The border features a bold scalloped design with leaf motifs, and the body has a delicate star motif.', 'pyor-gotta-patti-saree-wine', 3950, 'Pyor Gotta Patti (21).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A beautiful deep plum saree featuring intricate Gota Patti work and pearl detailing. The border has a detailed leaf pattern with a bold floral motif on the body.', 'pyor-gotta-patti-saree-deep-plum', 3950, 'Pyor Gotta Patti (22).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A rich maroon saree with a combination of golden and silver Gota Patti work. The border features a detailed floral pattern, with bold floral motifs on the body.', 'pyor-gotta-patti-saree-maroon-gota-patti', 4000, 'Pyor Gotta Patti (23).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A striking deep maroon saree with dense golden Gota Patti work. The saree features a heavy border with floral motifs and a single large floral motif on the pallu.', 'pyor-gotta-patti-saree-deep-maroon', 3950, 'Pyor Gotta Patti (24).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'An elegant plum saree with detailed Gota Patti work. The border is a bold and dense floral pattern, with a large circular floral motif on the pallu.', 'pyor-gotta-patti-saree-plum-floral', 3600, 'Pyor Gotta Patti (25).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A stunning brown saree featuring intricate Gota Patti work. The border combines geometric and floral patterns, with a detailed floral design on the pallu and scattered motifs on the body.', 'pyor-gotta-patti-saree-brown-floral', 3800, 'Pyor Gotta Patti (26).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A beautiful mauve saree featuring intricate Gota Patti work. The border showcases a detailed peacock and floral design, with a single leaf motif on the body.', 'pyor-gotta-patti-saree-mauve', 3800, 'Pyor Gotta Patti (27).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A luxurious deep green saree with Gota Patti and stone work. The border has a detailed leaf pattern with a bold floral motif and a center stone on the body.', 'pyor-gotta-patti-saree-deep-green', 3400, 'Pyor Gotta Patti (28).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A deep purple saree with intricate Gota Patti work and sequin details. The border features a geometric pattern, with a delicate floral motif on the body.', 'pyor-gotta-patti-saree-deep-purple', 3600, 'Pyor Gotta Patti (29).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'An elegant magenta saree with a classic Gota Patti border. The saree is adorned with intricate floral and leaf motifs and has a large circular floral motif on the body.', 'pyor-gotta-patti-saree-magenta-2', 3600, 'Pyor Gotta Patti (30).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A festive red saree with intricate Gota Patti work. The border features a scalloped leaf pattern, and the body has a large circular motif with delicate flowers and connecting lines.', 'pyor-gotta-patti-saree-red-2', 3400, 'Pyor Gotta Patti (31).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A rich plum saree with heavy Gota Patti work. The scalloped border features bold leaf motifs with a stunning star motif on the body of the saree.', 'pyor-gotta-patti-saree-plum', 3800, 'Pyor Gotta Patti (32).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A vibrant yellow saree with heavy silver Gota Patti work. The border features a dense floral and geometric pattern, with scattered leaf and floral motifs on the body.', 'pyor-gotta-patti-saree-yellow', 3600, 'Pyor Gotta Patti (33).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A stunning white saree with elaborate Gota Patti and mirror work. The border features a dense floral design with intricate patterns on the pallu and a contrasting red piping.', 'pyor-gotta-patti-saree-white', 3700, 'Pyor Gotta Patti (34).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A beautiful dark green saree with delicate Gota Patti work. The saree has a stunning border with floral motifs and is decorated with small scattered flowers on the body.', 'pyor-gotta-patti-saree-dark-green-2', 3150, 'Pyor Gotta Patti (35).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A charming pink saree with golden Gota Patti work. The saree features a border with zigzag and floral motifs and is decorated with small scattered floral motifs on the body.', 'pyor-gotta-patti-saree-pink-2', 3150, 'Pyor Gotta Patti (36).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A lovely rose pink saree with Gota Patti work. The border features a zigzag and floral design with small floral motifs scattered throughout the fabric.', 'pyor-gotta-patti-saree-rose-pink', 3150, 'Pyor Gotta Patti (37).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A graceful mauve saree with golden Gota Patti work. The border showcases a zigzag and floral design, with small floral motifs scattered on the body.', 'pyor-gotta-patti-saree-mauve-2', 3150, 'Pyor Gotta Patti (38).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A gorgeous magenta saree with golden Gota Patti work. The border features a detailed floral and zigzag pattern, with small scattered motifs on the body.', 'pyor-gotta-patti-saree-magenta-3', 3150, 'Pyor Gotta Patti (39).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A beautiful pista green saree with Gota Patti work. The border features a zigzag pattern with floral motifs and is decorated with small scattered flowers on the body.', 'pyor-gotta-patti-saree-pista-green-3', 3150, 'Pyor Gotta Patti (40).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A classic red saree with a heavy Gota Patti border. The border features a dense floral pattern with leaf motifs and a detailed floral design on the body of the saree.', 'pyor-gotta-patti-saree-red-3', 3400, 'Pyor Gotta Patti (41).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A stunning olive-green saree with intricate Gota Patti work. The saree features a border with elegant circular and floral motifs and delicate leaf designs on the body.', 'pyor-gotta-patti-saree-olive-green-2', 3900, 'Pyor Gotta Patti (42).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A beautiful pista green saree with silver Gota Patti work. The border showcases a detailed pattern of circular floral motifs, with scattered leaf designs on the body.', 'pyor-gotta-patti-saree-pista-green-4', 3900, 'Pyor Gotta Patti (43).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'An elegant lavender saree with heavy golden Gota Patti and mirror work. The saree features a scalloped border with intricate floral and mirror work, and a delicate floral brocade pattern.', 'pyor-gotta-patti-saree-lavender', 3700, 'Pyor Gotta Patti (44).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A beautiful mauve saree with intricate Gota Patti work. The border is adorned with a zigzag and leaf pattern, with a large leaf motif on the pallu.', 'pyor-gotta-patti-saree-mauve-3', 3200, 'Pyor Gotta Patti (45).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A sophisticated dusty pink saree with detailed Gota Patti and mirror work. The border features a scalloped design with floral and leaf motifs, with a subtle brocade pattern on the fabric.', 'pyor-gotta-patti-saree-dusty-pink-2', 3200, 'Pyor Gotta Patti (46).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A stunning magenta saree with Gota Patti and mirror work. The border has a graceful zigzag and leaf pattern, with a bold floral motif on the pallu.', 'pyor-gotta-patti-saree-magenta-4', 3200, 'Pyor Gotta Patti (47).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A classic royal blue saree with intricate Gota Patti work. The border is a bold combination of geometric and floral motifs, with stunning floral designs scattered on the body.', 'pyor-gotta-patti-saree-royal-blue', 3500, 'Pyor Gotta Patti (48).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A stunning beige saree with intricate Gota Patti and mirror work. The saree features a broad border with floral and mirror motifs, with a small check pattern on the fabric.', 'pyor-gotta-patti-saree-beige', 3200, 'Pyor Gotta Patti (49).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'An elegant off-white saree with delicate golden Gota Patti work. The border has a beautiful scalloped floral design with sequins, and the body has a subtle check pattern with scattered motifs.', 'pyor-gotta-patti-saree-off-white', 3200, 'Pyor Gotta Patti (50).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'An elegant off-white saree with delicate golden Gota Patti work. The saree features a broad scalloped border with floral motifs and subtle scattered patterns on the body.', 'pyor-gotta-patti-saree-off-white-2', 3100, 'Pyor Gotta Patti (51).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A beautiful dusty rose saree with intricate Gota Patti work on a brocade pattern. The saree has a heavy scalloped border with floral motifs and a delicate brocade pattern on the fabric.', 'pyor-gotta-patti-saree-dusty-rose-brocade', 3100, 'Pyor Gotta Patti (52).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A beautiful dusty pink saree with intricate Gota Patti work. The saree has a stunning border with a combination of leaf and floral patterns, with a brocade pattern on the fabric.', 'pyor-gotta-patti-saree-dusty-pink-3', 3100, 'Pyor Gotta Patti (53).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'An elegant peach-colored saree with fine Gota Patti work. The border features a unique floral and zigzag pattern with scattered small floral motifs on the body.', 'pyor-gotta-patti-saree-peach', 3100, 'Pyor Gotta Patti (54).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'An elegant pink saree with intricate Gota Patti work on a brocade pattern. The saree has a stunning scalloped border with floral motifs and scattered patterns on the body.', 'pyor-gotta-patti-saree-pink-brocade-2', 3100, 'Pyor Gotta Patti (55).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A beautiful dusty grey saree with Gota Patti and mirror work. The border features a combination of floral and mirror patterns, with large floral motifs on the body.', 'pyor-gotta-patti-saree-dusty-grey-2', 3700, 'Pyor Gotta Patti  (56).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A gorgeous plum saree with intricate Gota Patti and mirror work. The saree features a scalloped border with intricate floral and mirror work, with a brocade pattern on the fabric.', 'pyor-gotta-patti-saree-plum-2', 39500, 'Pyor Gotta Patti  (57).jpg', CURDATE(), 0),
(6, 'Pyor Gotta Patti Saree', 'A stunning red saree with a heavy golden Gota Patti border. The saree has a broad scalloped border with leaf motifs and scattered star patterns on the body.', 'pyor-gotta-patti-saree-red-4', 3200, 'pyor Gotta Patti (58).jpg', CURDATE(), 0)
SQL;

// Replace INSERT INTO `products` with our logic
$lines = explode("\n", $sqlProducts);
$stmtProd = $db->prepare("INSERT INTO products (category_id, seller_id, title, description, status) VALUES (?, ?, ?, ?, ?)");
$stmtVar = $db->prepare("INSERT INTO product_variants (product_id, sku, price, wholesale_price, image_url, bulk_threshold, stock) VALUES (?, ?, ?, ?, ?, ?, ?)");

$totalProds = 0;
foreach ($lines as $line) {
    if (strpos($line, '(') === 0) {
        $line = rtrim($line, ',');
        $line = trim($line, "(), \r\n");
        // Parse the line manually. Since there are single quotes, we can use str_getcsv
        $fields = str_getcsv($line, ',', "'");
        if (count($fields) >= 6) {
            $cat_id = $fields[0];
            $name = trim($fields[1]);
            $desc = trim($fields[2]);
            $price = floatval($fields[4]);
            $photo = trim($fields[5]);
            
            $stmtProd->execute([$cat_id, 1, $name, $desc, 'ACTIVE']);
            $prod_id = $db->lastInsertId();
            
            $sku = strtoupper(substr(md5($name . $photo), 0, 8));
            $imageUrl = '/uploads/products/' . $photo;
            
            $stmtVar->execute([$prod_id, $sku, $price, $price, $imageUrl, 5, 100]);
            $totalProds++;
        }
    }
}

echo "Successfully inserted $totalProds products and variants.\n";
