<?php
spl_autoload_register(function ($class) { $b=__DIR__.'/'; $p=['Core\\'=>'core/','App\\'=>'src/']; foreach($p as $pr=>$d){ $l=strlen($pr); if(strncmp($pr,$class,$l)!==0)continue; $r=substr($class,$l); $f=$b.$d.str_replace('\\','/',$r).'.php'; if(file_exists($f)){require $f;return;} } });
$app = new \Core\Application();
$pdo = (new \ReflectionProperty($app->db, 'pdo'))->getValue($app->db);
$pdo->exec('SET FOREIGN_KEY_CHECKS = 0; TRUNCATE TABLE categories; TRUNCATE TABLE products; TRUNCATE TABLE product_variants; TRUNCATE TABLE product_images;');
$pdo->exec("INSERT IGNORE INTO users (id, name, email, mobile, password_hash, role_id, status) VALUES (1, 'Pavitra Seller', 'seller@pavitra.com', '9999999999', '', 1, 'ACTIVE')");
$stmtC = $pdo->prepare('INSERT INTO categories (id, name, slug) VALUES (?, ?, ?)');
$stmtC->execute([1, 'Bandhej Sarees', 'bandhej-sarees']);
$stmtC->execute([2, 'Banarasi Sarees', 'banarasi-sarees']);
$stmtC->execute([3, 'Gotta Patti Chunri Sarees', 'gotta-patti-sarees']);
$stmtC->execute([4, 'Pittan Work Sarees', 'pittan-work-sarees']);
$stmtC->execute([5, 'Printed Sarees', 'printed-sarees']);
$stmtC->execute([6, 'Pyor Gotta Patti Sarees', 'pyor-gotta-patti-sarees']);
$stmtP = $pdo->prepare('INSERT INTO products (id, category_id, seller_id, title, description, status, is_approved) VALUES (?, ?, 1, ?, ?, "ACTIVE", 1)');
$stmtV = $pdo->prepare('INSERT INTO product_variants (product_id, sku, price, wholesale_price, stock) VALUES (?, ?, ?, ?, 100)');
$stmtI = $pdo->prepare('INSERT INTO product_images (product_id, image_url, is_primary) VALUES (?, ?, 1)');
$stmtP->execute([1, 1, 'Royal Blue Bandhej Saree', 'A vibrant royal blue Bandhej saree with intricate white tie-dye patterns and a unique pallu featuring broad gold and dark blue stripes.']);
$stmtV->execute([1, 'SKU-00001', 4000, 3600]);
$stmtI->execute([1, '/uploads/products/Bandhej (1).jpg']);
$stmtP->execute([2, 1, 'Navy Blue and White Bandhej Saree', 'A striking navy blue Bandhej saree with a large, intricate white and light blue circular pattern on the pallu and a bold gold striped border.']);
$stmtV->execute([2, 'SKU-00002', 4500, 4050]);
$stmtI->execute([2, '/uploads/products/Bandhej (2).jpg']);
$stmtP->execute([3, 1, 'Teal Bandhej Saree', 'A rich teal Bandhej saree featuring small yellow dot patterns and a golden pallu with detailed motifs of human figures.']);
$stmtV->execute([3, 'SKU-00003', 4200, 3780]);
$stmtI->execute([3, '/uploads/products/Bandhej (3).jpg']);
$stmtP->execute([4, 1, 'Light Purple Bandhej Saree', 'A delicate light purple Bandhej saree with subtle white tie-dye dots and a wide, elegant golden border on the pallu.']);
$stmtV->execute([4, 'SKU-00004', 3800, 3420]);
$stmtI->execute([4, '/uploads/products/Bandhej (4).jpg']);
$stmtP->execute([5, 1, 'Red and Rainbow Bandhej Saree', 'A striking Bandhej saree with a red top half and a vibrant rainbow-striped bottom half, finished with a classic red and gold border.']);
$stmtV->execute([5, 'SKU-00005', 5000, 4500]);
$stmtI->execute([5, '/uploads/products/Bandhej (5).jpg']);
$stmtP->execute([6, 1, 'Classic Red Bandhej Saree', 'A traditional red Bandhej saree adorned with small white and yellow tie-dye dot patterns and a pallu featuring intricate white paisley designs and a golden border.']);
$stmtV->execute([6, 'SKU-00006', 4100, 3690]);
$stmtI->execute([6, '/uploads/products/Bandhej (6).jpg']);
$stmtP->execute([7, 1, 'Rainbow and Red Bandhej Saree', 'A vibrant Bandhej saree featuring a red top portion and a multi-colored rainbow-striped design, leading to a traditional red and gold woven border.']);
$stmtV->execute([7, 'SKU-00007', 5000, 4500]);
$stmtI->execute([7, '/uploads/products/Bandhej (7).jpg']);
$stmtP->execute([8, 1, 'Purple Geometric Bandhej Saree', 'A sophisticated purple Bandhej saree with complex geometric patterns in white and orange, complemented by an ornate golden border.']);
$stmtV->execute([8, 'SKU-00008', 4800, 4320]);
$stmtI->execute([8, '/uploads/products/Bandhej (8).jpg']);
$stmtP->execute([9, 1, 'Green Bandhej Saree', 'A bright green Bandhej saree with all-over intricate white and yellow patterns forming floral and geometric shapes.']);
$stmtV->execute([9, 'SKU-00009', 4300, 3870]);
$stmtI->execute([9, '/uploads/products/Bandhej (9).jpg']);
$stmtP->execute([10, 1, 'Coral Red Bandhej Saree', 'A beautiful coral red Bandhej saree with subtle white and orange tie-dye dots arranged in floral and diamond-shaped motifs across the fabric.']);
$stmtV->execute([10, 'SKU-00010', 4100, 3690]);
$stmtI->execute([10, '/uploads/products/Bandhej (10).jpg']);
$stmtP->execute([11, 1, 'Red and Pink Diamond Bandhej Saree', 'A vibrant Bandhej saree in a red and pink color combination, featuring distinct diamond-shaped patterns with intricate floral and dot motifs.']);
$stmtV->execute([11, 'SKU-00011', 5200, 4680]);
$stmtI->execute([11, '/uploads/products/Bandhej (11).jpg']);
$stmtP->execute([12, 1, 'Hot Pink and Red Bandhej Saree', 'A stunning hot pink Bandhej saree with prominent red and orange diamond patterns, each with a detailed floral center.']);
$stmtV->execute([12, 'SKU-00012', 5100, 4590]);
$stmtI->execute([12, '/uploads/products/Bandhej (12).jpg']);
$stmtP->execute([13, 1, 'Hot Pink Circle Bandhej Saree', 'This hot pink Bandhej saree features two large, prominent circular patterns created from fine white tie-dye dots, giving it a classic and delicate look.']);
$stmtV->execute([13, 'SKU-00013', 4900, 4410]);
$stmtI->execute([13, '/uploads/products/Bandhej (18).jpg']);
$stmtP->execute([14, 1, 'Green Circle Bandhej Saree', 'A bright green Bandhej saree with two prominent circular patterns created from fine white tie-dye dots, complemented by scattered dots across the fabric.']);
$stmtV->execute([14, 'SKU-00014', 5000, 4500]);
$stmtI->execute([14, '/uploads/products/Bandhej (19).jpg']);
$stmtP->execute([15, 1, 'Red and Orange Bandhej Saree', 'A vibrant red Bandhej saree with two large circular patterns that transition from orange to yellow and a deep red center, and fine wave-like patterns.']);
$stmtV->execute([15, 'SKU-00015', 5300, 4770]);
$stmtI->execute([15, '/uploads/products/Bandhej (20).jpg']);
$stmtP->execute([16, 1, 'Red and Hot Pink Circle Bandhej Saree', 'This vibrant red Bandhej saree features two large, circular designs in a bold hot pink with finely detailed concentric patterns.']);
$stmtV->execute([16, 'SKU-00016', 5200, 4680]);
$stmtI->execute([16, '/uploads/products/Bandhej (21).jpg']);
$stmtP->execute([17, 1, 'Red, Pink, and Gold Brocade Saree', 'A luxurious Bandhej saree that transitions from deep red to hot pink, adorned with a heavy gold woven brocade pattern and a broad, intricate gold border.']);
$stmtV->execute([17, 'SKU-00017', 6500, 5850]);
$stmtI->execute([17, '/uploads/products/Bandhej (23).jpg']);
$stmtP->execute([18, 1, 'Green and Gold Brocade Saree', 'An elegant dark green Bandhej saree with a rich, all-over gold woven brocade pattern featuring large paisley and geometric motifs, and a wide, detailed border.']);
$stmtV->execute([18, 'SKU-00018', 6800, 6120]);
$stmtI->execute([18, '/uploads/products/Bandhej (24).jpg']);
$stmtP->execute([19, 1, 'Blue, Green, and Gold Brocade Saree', 'A stunning saree that fades from royal blue to teal green, featuring an elaborate gold woven brocade pattern of floral and geometric shapes with a wide, decorative border.']);
$stmtV->execute([19, 'SKU-00019', 6700, 6030]);
$stmtI->execute([19, '/uploads/products/Bandhej (26).jpg']);
$stmtP->execute([20, 1, 'Magenta and Gold Brocade Saree', 'A rich magenta and hot pink Bandhej saree with a broad, ornate gold woven border and an all-over intricate gold pattern, reminiscent of a Banarasi weave.']);
$stmtV->execute([20, 'SKU-00020', 6600, 5940]);
$stmtI->execute([20, '/uploads/products/Bandhej (27).jpg']);
$stmtP->execute([21, 1, 'Royal Blue and Gold Brocade Saree', 'An elegant royal blue saree with an all-over heavy gold brocade pattern, including large paisley-like motifs and a diamond pattern, and a wide, intricate gold border.']);
$stmtV->execute([21, 'SKU-00021', 7200, 6480]);
$stmtI->execute([21, '/uploads/products/Bandhej (28).jpg']);
$stmtP->execute([22, 1, 'Pink, Green, and Gold Brocade Saree', 'A multi-colored saree that transitions from magenta and pink to green and gold, covered in a heavy gold brocade pattern featuring intricate leaf and floral motifs.']);
$stmtV->execute([22, 'SKU-00022', 7300, 6570]);
$stmtI->execute([22, '/uploads/products/Bandhej (30).jpg']);
$stmtP->execute([23, 1, 'Red and Gold Banarasi-style Saree', 'A traditional red saree with a lush gold woven pattern that combines large oval motifs with smaller floral patterns, and a wide, intricate gold border.']);
$stmtV->execute([23, 'SKU-00023', 7000, 6300]);
$stmtI->execute([23, '/uploads/products/Bandhej (31).jpg']);
$stmtP->execute([24, 1, 'Red and Gold Brocade Saree', 'This stunning red saree is adorned with a rich, all-over gold brocade pattern, featuring a mix of a large, intricate diamond pattern and a detailed leaf motif, with a heavy, ornate gold border.']);
$stmtV->execute([24, 'SKU-00024', 7100, 6390]);
$stmtI->execute([24, '/uploads/products/Bandhej (33).jpg']);
$stmtP->execute([25, 1, 'Teal Bandhej Saree', 'A beautiful teal Bandhej saree with an all-over fine white dot pattern and a pallu highlighted by a wide, striking gold border.']);
$stmtV->execute([25, 'SKU-00025', 4500, 4050]);
$stmtI->execute([25, '/uploads/products/Bandhej (35).jpg']);
$stmtP->execute([26, 1, 'Golden Yellow Bandhej Saree', 'A bright golden yellow Bandhej saree with small white dot patterns, and a wide, shimmery gold border on the pallu.']);
$stmtV->execute([26, 'SKU-00026', 4400, 3960]);
$stmtI->execute([26, '/uploads/products/Bandhej (36).jpg']);
$stmtP->execute([27, 1, 'Pink Saree', 'Bandhej']);
$stmtV->execute([27, 'SKU-00027', 3900, 3510]);
$stmtI->execute([27, '/uploads/products/Bandhej (37).jpg']);
$stmtP->execute([28, 1, 'Emerald Saree', 'Bandhej']);
$stmtV->execute([28, 'SKU-00028', 3900, 3510]);
$stmtI->execute([28, '/uploads/products/Bandhej (38).jpg']);
$stmtP->execute([29, 1, 'Mocha Saree', 'Bandhej']);
$stmtV->execute([29, 'SKU-00029', 3900, 3510]);
$stmtI->execute([29, '/uploads/products/Bandhej (39).jpg']);
$stmtP->execute([30, 1, 'Cobalt Saree', 'Bandhej']);
$stmtV->execute([30, 'SKU-00030', 3900, 3510]);
$stmtI->execute([30, '/uploads/products/Bandhej (40).jpg']);
$stmtP->execute([31, 1, 'Mahogany Saree', 'Bandhej']);
$stmtV->execute([31, 'SKU-00031', 3900, 3510]);
$stmtI->execute([31, '/uploads/products/Bandhej (41).jpg']);
$stmtP->execute([32, 1, 'Slate Saree', 'Bandhej']);
$stmtV->execute([32, 'SKU-00032', 3900, 3510]);
$stmtI->execute([32, '/uploads/products/Bandhej (42).jpg']);
$stmtP->execute([33, 1, 'Indigo Saree', 'Bandhej']);
$stmtV->execute([33, 'SKU-00033', 3900, 3510]);
$stmtI->execute([33, '/uploads/products/Bandhej (43).jpg']);
$stmtP->execute([34, 1, 'Lilac Saree', 'Bandhej']);
$stmtV->execute([34, 'SKU-00034', 3900, 3510]);
$stmtI->execute([34, '/uploads/products/Bandhej (44).jpg']);
$stmtP->execute([35, 1, 'Golden-Pink-Red Gotta Patti Bandhej', 'Oval and floral gold zari design']);
$stmtV->execute([35, 'SKU-00035', 5700, 5130]);
$stmtI->execute([35, '/uploads/products/gotta patti Bandhej (1).jpg']);
$stmtP->execute([36, 1, 'Golden-Pink-Red Gotta Patti Bandhej', 'Oval and floral gold zari design']);
$stmtV->execute([36, 'SKU-00036', 5700, 5130]);
$stmtI->execute([36, '/uploads/products/gotta patti Bandhej (2).jpg']);
$stmtP->execute([37, 1, 'Gotta Patti Bandhej Saree', 'Beautiful pink Bandhej saree with intricate gotta patti embroidery and golden border.']);
$stmtV->execute([37, 'SKU-00037', 5500, 4950]);
$stmtI->execute([37, '/uploads/products/gotta patti Bandhej (3).jpg']);
$stmtP->execute([38, 1, 'Gotta Patti Bandhej Saree', 'Elegant pink Bandhej saree with golden zari border and traditional patterns.']);
$stmtV->execute([38, 'SKU-00038', 5600, 5040]);
$stmtI->execute([38, '/patola.png']);
$stmtP->execute([39, 1, 'Gotta Patti Bandhej Saree', 'Red Bandhej saree with heavy gotta patti work and golden finishing.']);
$stmtV->execute([39, 'SKU-00039', 5800, 5220]);
$stmtI->execute([39, '/tissue.png']);
$stmtP->execute([40, 1, 'Gotta Patti Bandhej Saree', 'Royal red Bandhej saree with floral gotta patti embroidery and zari border.']);
$stmtV->execute([40, 'SKU-00040', 6000, 5400]);
$stmtI->execute([40, '/uploads/products/gotta patti Bandhej (6).jpg']);
$stmtP->execute([41, 1, 'Gotta Patti Bandhej Saree', 'Classic pink Bandhej saree with heavy border work and golden detailing.']);
$stmtV->execute([41, 'SKU-00041', 5700, 5130]);
$stmtI->execute([41, '/uploads/products/gotta patti Bandhej (7).jpg']);
$stmtP->execute([42, 1, 'Gotta Patti Bandhej Saree', 'Pink Bandhej saree featuring traditional diamond patterns and gotta patti finish.']);
$stmtV->execute([42, 'SKU-00042', 5600, 5040]);
$stmtI->execute([42, '/patola.png']);
$stmtP->execute([43, 1, 'Gotta Patti Bandhej Saree', 'Designer pink Bandhej saree with elephant and peacock motifs in gotta patti.']);
$stmtV->execute([43, 'SKU-00043', 6200, 5580]);
$stmtI->execute([43, '/tissue.png']);
$stmtP->execute([44, 1, 'Gotta Patti Bandhej Saree', 'Traditional Bandhej saree in magenta shade with heavy border work.']);
$stmtV->execute([44, 'SKU-00044', 5900, 5310]);
$stmtI->execute([44, '/kanjeevaram.png']);
$stmtP->execute([45, 1, 'Gotta Patti Bandhej Saree', 'Exclusive Bandhej saree with detailed floral gotta patti embroidery.']);
$stmtV->execute([45, 'SKU-00045', 6100, 5490]);
$stmtI->execute([45, '/uploads/products/gotta patti Bandhej (11).jpg']);
$stmtP->execute([46, 1, 'Gotta Patti Chunri Saree', 'Red Bandhej Chunri saree with intricate gotta patti border, floral motifs, and diamond-shaped Bandhej patterns.']);
$stmtV->execute([46, 'SKU-00046', 4600, 4140]);
$stmtI->execute([46, '/uploads/products/Gotta Patti Chunri (1).jpg']);
$stmtP->execute([47, 3, 'Red Bandhani Chunri', 'Traditional red bandhani saree with golden gotta patti border']);
$stmtV->execute([47, 'SKU-00047', 4800, 4320]);
$stmtI->execute([47, '/uploads/products/Gotta Patti Chunri (2).jpg']);
$stmtP->execute([48, 3, 'Magenta Bandhani Chunri', 'Elegant magenta bandhani saree with golden border']);
$stmtV->execute([48, 'SKU-00048', 4800, 4320]);
$stmtI->execute([48, '/uploads/products/Gotta Patti Chunri (3).jpg']);
$stmtP->execute([49, 3, 'Designer Bandhani Chunri', 'Handcrafted bandhani chunri with floral motifs and zari work']);
$stmtV->execute([49, 'SKU-00049', 4500, 4050]);
$stmtI->execute([49, '/uploads/products/Gotta Patti Chunri (4).jpg']);
$stmtP->execute([50, 3, 'Multicolor Bandhani Chunri', 'Red saree with multicolor bandhani designs and gotta work']);
$stmtV->execute([50, 'SKU-00050', 4500, 4050]);
$stmtI->execute([50, '/uploads/products/Gotta Patti Chunri (5).jpg']);
$stmtP->execute([51, 3, 'Classic Red Bandhani Chunri', 'Rich red bandhani saree with detailed golden border']);
$stmtV->execute([51, 'SKU-00051', 4800, 4320]);
$stmtI->execute([51, '/uploads/products/Gotta Patti Chunri (6).jpg']);
$stmtP->execute([52, 3, 'Red Bandhani with Floral Work', 'Chunri with red base, white bandhani dots and floral gotta motifs']);
$stmtV->execute([52, 'SKU-00052', 5000, 4500]);
$stmtI->execute([52, '/uploads/products/Gotta Patti Chunri (7).jpg']);
$stmtP->execute([53, 3, 'Velvet Style Bandhani Chunri', 'Luxurious velvet-look bandhani chunri with intricate gotta patti border']);
$stmtV->execute([53, 'SKU-00053', 4900, 4410]);
$stmtI->execute([53, '/uploads/products/Gotta Patti Chunri (8).jpg']);
$stmtP->execute([54, 3, 'Heavy Border Bandhani Chunri', 'Saree with heavy embroidery border and colorful motifs']);
$stmtV->execute([54, 'SKU-00054', 6000, 5400]);
$stmtI->execute([54, '/uploads/products/Gotta Patti Chunri (9).jpg']);
$stmtP->execute([55, 3, 'Dark Red Chunri - Intricate Silver Gota Patti', 'A stunning dark red chunri with a traditional bandhani pattern. The entire piece is richly adorned with intricate silver gota patti work, featuring elegant paisley and floral designs, perfect for weddings and special events.']);
$stmtV->execute([55, 'SKU-00055', 6200, 5580]);
$stmtI->execute([55, '/uploads/products/Gotta Patti Chunri (12).jpg']);
$stmtP->execute([56, 3, 'Red Gotta Patti Chunri - Peacock Design', 'Traditional red Chunri with intricate Gotta Patti and Peacock motifs']);
$stmtV->execute([56, 'SKU-00056', 4399, 3959.1]);
$stmtI->execute([56, '/uploads/products/Gotta Patti Chunri (13).jpg']);
$stmtP->execute([57, 3, 'Red Gotta Patti Chunri - Floral Border', 'Elegant Chunri featuring golden floral border embroidery with bandhani style dots']);
$stmtV->execute([57, 'SKU-00057', 5599, 5039.1]);
$stmtI->execute([57, '/uploads/products/Gotta Patti Chunri (14).jpg']);
$stmtP->execute([58, 3, 'Red Gotta Patti Chunri - Large Floral Pattern', 'Red Chunri with central floral embroidery and detailed border work']);
$stmtV->execute([58, 'SKU-00058', 4799, 4319.1]);
$stmtI->execute([58, '/uploads/products/Gotta Patti Chunri (15).jpg']);
$stmtP->execute([59, 3, 'Red Gotta Patti Chunri - Full Embroidery Border', 'Heavy border embroidered Chunri with delicate Gotta Patti details']);
$stmtV->execute([59, 'SKU-00059', 4799, 4319.1]);
$stmtI->execute([59, '/uploads/products/Gotta Patti Chunri (16).jpg']);
$stmtP->execute([60, 3, 'Red Gotta Patti Chunri - Traditional Bandhani Style', 'Traditional bandhani style Chunri enhanced with golden Gotta Patti border']);
$stmtV->execute([60, 'SKU-00060', 3399, 3059.1]);
$stmtI->execute([60, '/uploads/products/Gotta Patti Chunri (17).jpg']);
$stmtP->execute([61, 3, 'Red Gotta Patti Chunri - Golden Leaf Border', 'Red Chunri featuring golden leaf motifs and Gotta Patti embellishments']);
$stmtV->execute([61, 'SKU-00061', 3599, 3239.1]);
$stmtI->execute([61, '/uploads/products/Gotta Patti Chunri (18).jpg']);
$stmtP->execute([62, 3, 'Red Gotta Patti Chunri - Wedding Special', 'Special wedding Chunri with intricate Gotta Patti and peacock motifs']);
$stmtV->execute([62, 'SKU-00062', 3999, 3599.1]);
$stmtI->execute([62, '/uploads/products/Gotta Patti Chunri (19).jpg']);
$stmtP->execute([63, 3, 'Red Gotta Patti Chunri - Designer Border', 'Designer Chunri with diamond patterned embroidery and golden lace border']);
$stmtV->execute([63, 'SKU-00063', 3899, 3509.1]);
$stmtI->execute([63, '/uploads/products/Gotta Patti Chunri (20).jpg']);
$stmtP->execute([64, 3, 'Red Gotta Patti Chunri - Royal Design', 'Royal style Chunri with detailed peacock, floral motifs and fine border work']);
$stmtV->execute([64, 'SKU-00064', 3399, 3059.1]);
$stmtI->execute([64, '/uploads/products/Gotta Patti Chunri (21).jpg']);
$stmtP->execute([65, 3, 'Red Bandhani Chunri - Scalloped Silver Border', 'A vibrant red bandhani chunri featuring a beautiful silver gota patti border with a scalloped edge and delicate floral designs. The main fabric has a classic dotted pattern with an elegant central motif.']);
$stmtV->execute([65, 'SKU-00065', 2650, 2385]);
$stmtI->execute([65, '/uploads/products/Gotta Patti Chunri (22).jpg']);
$stmtP->execute([66, 3, 'Red Bandhani Chunri - Silver Floral and Paisley', 'A traditional red chunri with a series of wavy and intricate bandhani patterns across the body. The chunri is finished with a striking silver gotta patti border featuring paisley and floral designs.']);
$stmtV->execute([66, 'SKU-00066', 2800, 2520]);
$stmtI->execute([66, '/uploads/products/Gotta Patti Chunri (23).jpg']);
$stmtP->execute([67, 3, 'Deep Red Chunri - Sun Motif and Silver Border', 'A stunning chunri in a deep red shade, showcasing a detailed bandhani tie-and-dye pattern with large, bright sun-like motifs. It is embellished with a decorative silver gotta patti border.']);
$stmtV->execute([67, 'SKU-00067', 3450, 3105]);
$stmtI->execute([67, '/uploads/products/Gotta Patti Chunri (24).jpg']);
$stmtP->execute([68, 3, 'Red and Orange Chunri - Wavy Silver Gota Work', 'An elegant chunri in red and orange with intricate wavy and paisley patterns in silver gotta patti. The border is finished with a detailed floral motif design, perfect for festive wear.']);
$stmtV->execute([68, 'SKU-00068', 3050, 2745]);
$stmtI->execute([68, '/uploads/products/Gotta Patti Chunri (25).jpg']);
$stmtP->execute([69, 3, 'Pinkish-Red Bandhani Chunri - Sunburst Gota Patti', 'A vibrant chunri in a beautiful mix of pink and red. This piece features a traditional dotted bandhani pattern with large, eye-catching sunburst motifs and a silver gotta patti border.']);
$stmtV->execute([69, 'SKU-00069', 3500, 3150]);
$stmtI->execute([69, '/uploads/products/Gotta Patti Chunri (26).jpg']);
$stmtP->execute([70, 3, 'Red Chunri - Detailed Silver Gota Patti Border', 'A classic red bandhani chunri that is heavily adorned with intricate silver gotta patti work. The detailed border features a scalloped edge and elaborate floral designs, adding a rich look to the piece.']);
$stmtV->execute([70, 'SKU-00070', 4000, 3600]);
$stmtI->execute([70, '/uploads/products/Gotta Patti Chunri (27).jpg']);
$stmtP->execute([71, 3, 'Red and Orange Chunri - Large Floral Motifs', 'This chunri combines a traditional red and orange bandhani pattern with large floral motifs scattered across the fabric. The border is a wide, intricate silver gotta patti design, creating a bold and beautiful statement.']);
$stmtV->execute([71, 'SKU-00071', 3300, 2970]);
$stmtI->execute([71, '/uploads/products/Gotta Patti Chunri (28).jpg']);
$stmtP->execute([72, 3, 'Red Bandhani Chunri - Diamond and Circular Motifs', 'A traditional red bandhani chunri featuring a large diamond-shaped motif and several concentric circular patterns. The border is heavily embellished with silver gotta patti in a floral design, adding elegance to the piece.']);
$stmtV->execute([72, 'SKU-00072', 2600, 2340]);
$stmtI->execute([72, '/uploads/products/Gotta Patti Chunri (29).jpg']);
$stmtP->execute([73, 3, 'Red Bandhani Chunri - Golden Wavy Gota Work', 'A rich red chunri with a traditional dotted bandhani pattern and a luxurious gold gotta patti border. The intricate design features wavy and circular patterns, giving it a classic and festive appeal.']);
$stmtV->execute([73, 'SKU-00073', 3700, 3330]);
$stmtI->execute([73, '/uploads/products/Gotta Patti Chunri (30).jpg']);
$stmtP->execute([74, 3, 'Red Chunri - Silver and Gold Gota Patti Border', 'A beautiful red chunri with a traditional bandhani pattern. It is uniquely embellished with both silver and gold gotta patti work, creating a dual-toned, rich border effect with wavy and paisley motifs.']);
$stmtV->execute([74, 'SKU-00074', 3300, 2970]);
$stmtI->execute([74, '/uploads/products/Gotta Patti Chunri (31).jpg']);
$stmtP->execute([75, 3, 'Dark Red Chunri - Orange Sun Motifs', 'A dark red chunri with a beautiful bandhani pattern. It is decorated with large, vibrant orange sun-like motifs and a detailed silver gota patti border, giving it a rich and festive appearance.']);
$stmtV->execute([75, 'SKU-00075', 2800, 2520]);
$stmtI->execute([75, '/uploads/products/Gotta Patti Chunri (32).jpg']);
$stmtP->execute([76, 3, 'Maroon Chunri - Gold Gota Patti and Paisley', 'A stunning maroon chunri with a traditional bandhani pattern. The entire piece is richly adorned with intricate gold gota patti work, featuring elegant paisley and floral designs, perfect for weddings and special events.']);
$stmtV->execute([76, 'SKU-00076', 4600, 4140]);
$stmtI->execute([76, '/uploads/products/Gotta Patti Chunri (33).jpg']);
$stmtP->execute([77, 3, 'Maroon Chunri - Silver and Gold Gota Patti', 'A stunning maroon chunri with a traditional bandhani pattern. The entire piece is richly adorned with intricate silver and gold gota patti work, featuring elegant paisley and floral designs, perfect for special events.']);
$stmtV->execute([77, 'SKU-00077', 3250, 2925]);
$stmtI->execute([77, '/uploads/products/Gotta Patti Chunri (34).jpg']);
$stmtP->execute([78, 3, 'Maroon Chunri - Wavy Silver Gota Patti', 'This maroon chunri features a traditional bandhani pattern with wavy and circular designs. The wide silver gota patti border, adorned with a floral and leaf pattern, adds a touch of sophistication.']);
$stmtV->execute([78, 'SKU-00078', 4850, 4365]);
$stmtI->execute([78, '/uploads/products/Gotta Patti Chunri (35).jpg']);
$stmtP->execute([79, 3, 'Dark Red Chunri - Large Sun Motifs', 'A dark red chunri with a traditional bandhani pattern. It is decorated with large, vibrant orange and silver sun-like motifs and a detailed silver gota patti border, giving it a rich and festive appearance.']);
$stmtV->execute([79, 'SKU-00079', 4300, 3870]);
$stmtI->execute([79, '/uploads/products/Gotta Patti Chunri (36).jpg']);
$stmtP->execute([80, 3, 'Maroon Chunri - Leafy Silver Gota Patti', 'This elegant maroon chunri features a subtle bandhani pattern and is bordered with intricate silver gota patti work. The border showcases a beautiful leafy and floral design, perfect for adding a touch of grace to any outfit.']);
$stmtV->execute([80, 'SKU-00080', 4900, 4410]);
$stmtI->execute([80, '/uploads/products/Gotta Patti Chunri (37).jpg']);
$stmtP->execute([81, 3, 'Red and Orange Chunri - Circular Gota Patti', 'A folded red and orange chunri with intricate bandhani patterns in concentric circles and diamonds. The piece is bordered with a detailed silver gota patti design featuring floral motifs.']);
$stmtV->execute([81, 'SKU-00081', 2800, 2520]);
$stmtI->execute([81, '/uploads/products/Gotta Patti Chunri (38).jpg']);
$stmtP->execute([82, 3, 'Maroon Bandhani Chunri - Floral Sun Motifs', 'This maroon chunri features a traditional dotted bandhani pattern with large, eye-catching floral-sun motifs. The border is finished with intricate silver gotta patti work, perfect for any festive occasion.']);
$stmtV->execute([82, 'SKU-00082', 2950, 2655]);
$stmtI->execute([82, '/uploads/products/Gotta Patti Chunri (39).jpg']);
$stmtP->execute([83, 3, 'Maroon Chunri - Silver Floral and Paisley', 'A traditional maroon chunri with a series of wavy and intricate bandhani patterns across the body. The chunri is finished with a striking silver gota patti border featuring paisley and floral designs.']);
$stmtV->execute([83, 'SKU-00083', 2850, 2565]);
$stmtI->execute([83, '/uploads/products/Gotta Patti Chunri (40).jpg']);
$stmtP->execute([84, 3, 'Maroon Chunri - Leafy Border with Silver Gota Patti', 'This maroon chunri features an elegant bandhani pattern with scattered floral motifs. The border is a highlight, with intricate silver gota patti work showcasing a beautiful leafy and floral design.']);
$stmtV->execute([84, 'SKU-00084', 4500, 4050]);
$stmtI->execute([84, '/uploads/products/Gotta Patti Chunri (41).jpg']);
$stmtP->execute([85, 3, 'Folded Red Chunri - Gota Patti Sun and Floral', 'A folded red chunri showcasing a beautiful central sun motif and other floral designs in silver gota patti. The entire piece is bordered with intricate silver gota patti work, highlighting its craftsmanship.']);
$stmtV->execute([85, 'SKU-00085', 2900, 2610]);
$stmtI->execute([85, '/uploads/products/Gotta Patti Chunri (42).jpg']);
$stmtP->execute([86, 3, 'Red Silk Chunri - Gold Gota Patti and Checkered Pattern', 'A luxurious red silk chunri with a lustrous finish. The chunri features a unique checkered bandhani pattern and is bordered with a rich gold gota patti design, perfect for an opulent and traditional look.']);
$stmtV->execute([86, 'SKU-00086', 3500, 3150]);
$stmtI->execute([86, '/uploads/products/Gotta Patti Chunri (43).jpg']);
$stmtP->execute([87, 3, 'Maroon Chunri - Pink and Silver Paisley', 'A maroon chunri with a traditional bandhani pattern and a detailed silver gota patti border. The border features a beautiful paisley design with subtle pink accents, adding a unique touch of color.']);
$stmtV->execute([87, 'SKU-00087', 3200, 2880]);
$stmtI->execute([87, '/uploads/products/Gotta Patti Chunri (44).jpg']);
$stmtP->execute([88, 3, 'Red Chunri - Intricate Golden Gota Patti', 'A stunning red chunri with a grid-like pattern of golden gota patti. The border is heavily embellished with intricate golden embroidery and mirror work, giving the piece a rich and luxurious feel.']);
$stmtV->execute([88, 'SKU-00088', 2800, 2520]);
$stmtI->execute([88, '/uploads/products/Gotta Patti Chunri (45).jpg']);
$stmtP->execute([89, 3, 'Maroon Chunri - Leafy and Floral Gota Patti', 'This elegant maroon chunri features a subtle bandhani pattern and is bordered with intricate silver gota patti work. The border showcases a beautiful leafy and floral design with small, scattered motifs.']);
$stmtV->execute([89, 'SKU-00089', 3700, 3330]);
$stmtI->execute([89, '/uploads/products/Gotta Patti Chunri (46).jpg']);
$stmtP->execute([90, 3, 'Red Chunri - Large Circular Gota Patti Motif', 'A striking red chunri featuring a very large, intricate circular motif made of silver gota patti. The rest of the chunri has a classic bandhani pattern and a beautiful floral silver gota patti border.']);
$stmtV->execute([90, 'SKU-00090', 3100, 2790]);
$stmtI->execute([90, '/uploads/products/Gotta Patti Chunri (47).jpg']);
$stmtP->execute([91, 3, 'Red and Orange Bandhani Chunri - Sunbursts', 'A vibrant chunri in red and orange, showcasing a traditional dotted bandhani pattern with large, bright sunburst motifs. It is finished with a decorative silver and gold gota patti border, perfect for festive occasions.']);
$stmtV->execute([91, 'SKU-00091', 4900, 4410]);
$stmtI->execute([91, '/uploads/products/Gotta Patti Chunri (48).jpg']);
$stmtP->execute([92, 3, 'Maroon Chunri - Orange Sun Motifs with Silver Gota', 'A maroon chunri featuring a traditional bandhani dotted pattern and large orange sun-like motifs. It is finished with a wide and intricate silver gotta patti border, perfect for adding a touch of traditional elegance to any outfit.']);
$stmtV->execute([92, 'SKU-00092', 3100, 2790]);
$stmtI->execute([92, '/uploads/products/Gotta Patti Chunri (49).jpg']);
$stmtP->execute([93, 3, 'Red Chunri - Golden Gota with Sunbursts', 'A luxurious red chunri with a smooth finish. This piece is a modern take on traditional design, featuring multiple lines of golden gota work with scattered sunburst motifs. The wide golden border adds to its grandeur.']);
$stmtV->execute([93, 'SKU-00093', 2500, 2250]);
$stmtI->execute([93, '/banarasi.png']);
$stmtP->execute([94, 4, 'Crimson Red Pittan Work Saree', 'A striking crimson red saree with classic Pittan work, making it an ideal choice for celebrations and traditional events.']);
$stmtV->execute([94, 'SKU-00094', 3750, 3375]);
$stmtI->execute([94, '/uploads/products/Pittan work (1).jpg']);
$stmtP->execute([95, 4, 'Pink Pittan Work Saree', 'Embrace a vibrant look with this beautiful pink saree, highlighted by exquisite Pittan work. The striking color combined with the detailed craftsmanship on the border and pallu offers a festive and celebratory feel.']);
$stmtV->execute([95, 'SKU-00095', 3750, 3375]);
$stmtI->execute([95, '/uploads/products/Pittan work (2).jpg']);
$stmtP->execute([96, 4, 'Mauve Pittan Work Saree', 'A stunning Mauve saree adorned with delicate Pittan work. The soft color and shimmering gold embroidery create a regal look, ideal for evening events and formal gatherings where you want to make a sophisticated statement.']);
$stmtV->execute([96, 'SKU-00096', 3750, 3375]);
$stmtI->execute([96, '/uploads/products/Pittan work (3).jpg']);
$stmtP->execute([97, 4, 'Green Pittan Work Saree', 'This elegant green saree features intricate Pittan work, a traditional Rajasthani embroidery technique. The rich detailing on the border and scattered motifs on the body make it perfect for weddings, festivals, and other special occasions.']);
$stmtV->execute([97, 'SKU-00097', 3750, 3375]);
$stmtI->execute([97, '/uploads/products/Pittan work (4).jpg']);
$stmtP->execute([98, 4, 'Magenta Pittan Work Saree', 'A gorgeous magenta saree with intricate Pittan work, making it a bold and beautiful statement piece for any celebration.']);
$stmtV->execute([98, 'SKU-00098', 3750, 3375]);
$stmtI->execute([98, '/uploads/products/Pittan work (5).jpg']);
$stmtP->execute([99, 4, 'Plum Purple Pittan Work Saree', 'A royal plum purple saree featuring exquisite Pittan work along the borders, offering a sophisticated and elegant look.']);
$stmtV->execute([99, 'SKU-00099', 3750, 3375]);
$stmtI->execute([99, '/uploads/products/Pittan work (6).jpg']);
$stmtP->execute([100, 4, 'Fuchsia Pink Pittan Work Saree', 'A vibrant fuchsia saree adorned with detailed Pittan work on the borders and small motifs across the body, perfect for festive occasions.']);
$stmtV->execute([100, 'SKU-00100', 3750, 3375]);
$stmtI->execute([100, '/uploads/products/Pittan work (7).jpg']);
$stmtP->execute([101, 4, 'Mustard Yellow Pittan Work Saree', 'A vibrant mustard yellow saree with contrasting silver Pittan work on the border and motifs, offering a bright and cheerful look.']);
$stmtV->execute([101, 'SKU-00101', 3750, 3375]);
$stmtI->execute([101, '/uploads/products/Pittan work (8).jpg']);
$stmtP->execute([102, 4, 'Dusty Rose Pittan Work Saree', 'This elegant saree in a dusty rose shade features a delicate self-woven floral pattern and a scalloped border with intricate Pittan work.']);
$stmtV->execute([102, 'SKU-00102', 3750, 3375]);
$stmtI->execute([102, '/uploads/products/Pittan work (9).jpg']);
$stmtP->execute([103, 4, 'Dusty Rose Pittan Work Saree', 'This elegant saree features a self-woven floral pattern and a scalloped border with intricate Pittan work, creating a sophisticated and luxurious look.']);
$stmtV->execute([103, 'SKU-00103', 3750, 3375]);
$stmtI->execute([103, '/uploads/products/Pittan work (10).jpg']);
$stmtP->execute([104, 4, 'Violet Crushed Pittan Work Saree', 'This unique violet saree features a crushed fabric texture with delicate gold Pittan motifs and a scalloped border, perfect for a contemporary festive style.']);
$stmtV->execute([104, 'SKU-00104', 3350, 3015]);
$stmtI->execute([104, '/uploads/products/Pittan work (11).jpg']);
$stmtP->execute([105, 4, 'Aqua Blue Pittan Work Saree', 'This soothing aqua blue saree features a subtle self-woven pattern and is beautifully embellished with detailed Pittan work on the borders, perfect for a chic and elegant event.']);
$stmtV->execute([105, 'SKU-00105', 3750, 3375]);
$stmtI->execute([105, '/uploads/products/Pittan work (12).jpg']);
$stmtP->execute([106, 4, 'Mint Green Pittan Work Saree', 'This serene mint green saree features a subtle self-woven pattern with shimmering Pittan work on the borders, creating a graceful and light festive outfit.']);
$stmtV->execute([106, 'SKU-00106', 3750, 3375]);
$stmtI->execute([106, '/uploads/products/Pittan work (13).jpg']);
$stmtP->execute([107, 4, 'Dusty Rose Pittan Saree with Floral Pattern', 'This luxurious dusty rose saree combines a self-woven floral pattern with a beautiful scalloped border, meticulously handcrafted with Pittan work and small bead detailing.']);
$stmtV->execute([107, 'SKU-00107', 3750, 3375]);
$stmtI->execute([107, '/uploads/products/Pittan work (14).jpg']);
$stmtP->execute([108, 4, 'Mustard Yellow Pittan Saree with Scalloped Border', 'A vibrant mustard yellow saree featuring an intricately designed scalloped border with shimmering silver and pink Pittan work, perfect for adding a pop of color to any festive look.']);
$stmtV->execute([108, 'SKU-00108', 3750, 3375]);
$stmtI->execute([108, '/uploads/products/Pittan work (15).jpg']);
$stmtP->execute([109, 4, 'Forest Green Pittan Saree with Scalloped Border', 'A rich forest green saree with a classic look, highlighted by a detailed scalloped border featuring a blend of silver and pink Pittan work and fine embroidery.']);
$stmtV->execute([109, 'SKU-00109', 3750, 3375]);
$stmtI->execute([109, '/uploads/products/Pittan work (16).jpg']);
$stmtP->execute([110, 4, 'Off-White Crushed Saree with Pittan Motifs', 'An elegant off-white saree with a stylish crushed texture, beautifully embellished with scattered golden Pittan motifs and a matching scalloped border for a sophisticated appearance.']);
$stmtV->execute([110, 'SKU-00110', 3350, 3015]);
$stmtI->execute([110, '/uploads/products/Pittan work (17).jpg']);
$stmtP->execute([111, 4, 'Dusty Blue Crushed Saree with Pittan Motifs', 'This elegant saree in a beautiful dusty blue shade features a crushed texture and is adorned with delicate Pittan motifs scattered across the body, finished with a simple scalloped border.']);
$stmtV->execute([111, 'SKU-00111', 3350, 3015]);
$stmtI->execute([111, '/uploads/products/Pittan work (18).jpg']);
$stmtP->execute([112, 5, 'Navy Blue Paisley Printed Saree', 'A comfortable and stylish printed saree featuring a striking navy blue base with intricate red and white paisley and geometric patterns, ideal for daily wear or casual events.']);
$stmtV->execute([112, 'SKU-00112', 3750, 3375]);
$stmtI->execute([112, '/uploads/products/Printed (1).jpg']);
$stmtP->execute([113, 5, 'Purple Paisley Printed Saree', 'A comfortable and stylish printed saree featuring a rich purple base with intricate pink and white paisley and geometric patterns, ideal for daily wear or casual events.']);
$stmtV->execute([113, 'SKU-00113', 3750, 3375]);
$stmtI->execute([113, '/uploads/products/Printed (2).jpg']);
$stmtP->execute([114, 5, 'Red Paisley Printed Saree', 'A comfortable and stylish printed saree featuring a vibrant red base with intricate black and white paisley and geometric patterns, ideal for daily wear or casual events.']);
$stmtV->execute([114, 'SKU-00114', 3750, 3375]);
$stmtI->execute([114, '/uploads/products/Printed (3).jpg']);
$stmtP->execute([115, 5, 'Navy Blue Paisley Printed Saree', 'A comfortable and stylish printed saree featuring a striking navy blue base with intricate red and white paisley and geometric patterns, ideal for daily wear or casual events.']);
$stmtV->execute([115, 'SKU-00115', 3750, 3375]);
$stmtI->execute([115, '/uploads/products/Printed (4).jpg']);
$stmtP->execute([116, 5, 'Pink Floral Motif Printed Saree', 'A rich pink saree with a delicate all-over floral motif and a heavy, ornate border, perfect for weddings and formal gatherings.']);
$stmtV->execute([116, 'SKU-00116', 3050, 2745]);
$stmtI->execute([116, '/uploads/products/Printed (5).jpg']);
$stmtP->execute([117, 5, 'Magenta Elephant and Geometric Printed Saree', 'A stunning magenta saree with a detailed elephant and geometric pattern on the pallu and body, perfect for special occasions and festive wear.']);
$stmtV->execute([117, 'SKU-00117', 3050, 2745]);
$stmtI->execute([117, '/uploads/products/Printed (6).jpg']);
$stmtP->execute([118, 5, 'Purple Floral Bandhani Printed Saree', 'A purple saree with a traditional floral bandhani print, featuring a detailed border and a unique floral design on the pallu, suitable for traditional events.']);
$stmtV->execute([118, 'SKU-00118', 3050, 2745]);
$stmtI->execute([118, '/uploads/products/Printed (7).jpg']);
$stmtP->execute([119, 5, 'Red Geometric Floral Printed Saree', 'A vibrant red saree with a detailed geometric and floral print, featuring a striking floral border, ideal for festive events and celebrations.']);
$stmtV->execute([119, 'SKU-00119', 3050, 2745]);
$stmtI->execute([119, '/uploads/products/Printed (8).jpg']);
$stmtP->execute([120, 5, 'Pink Geometric Floral Printed Saree', 'A vibrant pink saree with a detailed geometric and floral print, featuring a striking floral border, ideal for festive events and celebrations.']);
$stmtV->execute([120, 'SKU-00120', 3050, 2745]);
$stmtI->execute([120, '/uploads/products/Printed (9).jpg']);
$stmtP->execute([121, 5, 'Purple Floral Motif Printed Saree', 'A rich purple saree with a delicate all-over floral motif and a heavy, ornate border, perfect for weddings and formal gatherings.']);
$stmtV->execute([121, 'SKU-00121', 3050, 2745]);
$stmtI->execute([121, '/uploads/products/Printed (10).jpg']);
$stmtP->execute([122, 5, 'Purple Elephant and Geometric Printed Saree', 'A stunning purple saree with a detailed elephant and geometric pattern on the pallu and body, perfect for special occasions and festive wear.']);
$stmtV->execute([122, 'SKU-00122', 3050, 2745]);
$stmtI->execute([122, '/uploads/products/Printed (11).jpg']);
$stmtP->execute([123, 5, 'Purple Geometric Floral Printed Saree', 'A vibrant purple saree with a detailed geometric and floral print, featuring a striking floral border, ideal for festive events and celebrations.']);
$stmtV->execute([123, 'SKU-00123', 3050, 2745]);
$stmtI->execute([123, '/uploads/products/Printed (12).jpg']);
$stmtP->execute([124, 5, 'Magenta Floral Bandhani Printed Saree', 'A magenta saree with a traditional floral bandhani print, featuring a detailed border and a unique floral design on the pallu, suitable for traditional events.']);
$stmtV->execute([124, 'SKU-00124', 3050, 2745]);
$stmtI->execute([124, '/uploads/products/Printed (13).jpg']);
$stmtP->execute([125, 5, 'Pink Floral Bandhani Printed Saree', 'A pink saree with a traditional floral bandhani print, featuring a detailed border and a unique floral design on the pallu, suitable for traditional events.']);
$stmtV->execute([125, 'SKU-00125', 3050, 2745]);
$stmtI->execute([125, '/uploads/products/Printed (14).jpg']);
$stmtP->execute([126, 5, 'Pink Elephant and Geometric Printed Saree', 'A stunning pink saree with a detailed elephant and geometric pattern on the pallu and body, perfect for special occasions and festive wear.']);
$stmtV->execute([126, 'SKU-00126', 3050, 2745]);
$stmtI->execute([126, '/uploads/products/Printed (15).jpg']);
$stmtP->execute([127, 5, 'Yellow Elephant and Geometric Printed Saree', 'A stunning yellow saree with a detailed elephant and geometric pattern on the pallu and body, perfect for special occasions and festive wear.']);
$stmtV->execute([127, 'SKU-00127', 3050, 2745]);
$stmtI->execute([127, '/uploads/products/Printed (16).jpg']);
$stmtP->execute([128, 5, 'Pink Floral Motif Printed Saree', 'A vibrant pink saree featuring large, intricate floral motifs, perfect for a chic and traditional look.']);
$stmtV->execute([128, 'SKU-00128', 3050, 2745]);
$stmtI->execute([128, '/uploads/products/Printed (17).jpg']);
$stmtP->execute([129, 5, 'Dark Purple Elephant and Geometric Printed Saree', 'A stunning dark purple saree with a detailed elephant and geometric pattern on the pallu and body, perfect for special occasions and festive wear.']);
$stmtV->execute([129, 'SKU-00129', 3050, 2745]);
$stmtI->execute([129, '/uploads/products/Printed (18).jpg']);
$stmtP->execute([130, 5, 'Purple Floral Bandhani Printed Saree', 'A purple saree with a traditional floral bandhani print, featuring a detailed border and a unique floral design on the pallu, suitable for traditional events.']);
$stmtV->execute([130, 'SKU-00130', 3050, 2745]);
$stmtI->execute([130, '/uploads/products/Printed (19).jpg']);
$stmtP->execute([131, 5, 'Red Elephant and Geometric Saree', 'A stunning red saree with a detailed elephant and geometric pattern on the pallu and body, perfect for special occasions and festive wear.']);
$stmtV->execute([131, 'SKU-00131', 3050, 2745]);
$stmtI->execute([131, '/uploads/products/Printed (20).jpg']);
$stmtP->execute([132, 5, 'Magenta Floral Bandhani Saree', 'A magenta saree with a traditional floral bandhani print, featuring a detailed border and a unique floral design on the pallu, suitable for traditional events.']);
$stmtV->execute([132, 'SKU-00132', 3050, 2745]);
$stmtI->execute([132, '/uploads/products/Printed (21).jpg']);
$stmtP->execute([133, 5, 'Purple Floral Motif Saree', 'A rich purple saree with a delicate all-over floral motif and a heavy, ornate border, perfect for weddings and formal gatherings.']);
$stmtV->execute([133, 'SKU-00133', 3050, 2745]);
$stmtI->execute([133, '/uploads/products/Printed (22).jpg']);
$stmtP->execute([134, 5, 'Pink Floral Motif Saree', 'A rich pink saree with a delicate all-over floral motif and a heavy, ornate border, perfect for weddings and formal gatherings.']);
$stmtV->execute([134, 'SKU-00134', 3050, 2745]);
$stmtI->execute([134, '/uploads/products/Printed (23).jpg']);
$stmtP->execute([135, 5, 'Pink Geometric and Floral Saree', 'A vibrant pink saree with a detailed geometric and floral print, featuring a striking floral border, ideal for festive events and celebrations.']);
$stmtV->execute([135, 'SKU-00135', 3050, 2745]);
$stmtI->execute([135, '/uploads/products/Printed (24).jpg']);
$stmtP->execute([136, 5, 'Red Geometric and Floral Saree', 'A vibrant red saree with a detailed geometric and floral print, featuring a striking floral border, ideal for festive events and celebrations.']);
$stmtV->execute([136, 'SKU-00136', 3050, 2745]);
$stmtI->execute([136, '/uploads/products/Printed (25).jpg']);
$stmtP->execute([137, 5, 'Dark Purple Floral Bandhani Saree', 'A dark purple saree with a traditional floral bandhani print, featuring a detailed border and a unique floral design on the pallu, suitable for traditional events.']);
$stmtV->execute([137, 'SKU-00137', 3050, 2745]);
$stmtI->execute([137, '/uploads/products/Printed (26).jpg']);
$stmtP->execute([138, 5, 'Maroon Floral Motif Saree', 'A rich maroon saree with a delicate all-over floral motif and a heavy, ornate border, perfect for weddings and formal gatherings.']);
$stmtV->execute([138, 'SKU-00138', 3050, 2745]);
$stmtI->execute([138, '/uploads/products/Printed (27).jpg']);
$stmtP->execute([139, 5, 'Yellow Geometric and Floral Saree', 'A vibrant yellow saree with a detailed geometric and floral print, featuring a striking floral border, ideal for festive events and celebrations.']);
$stmtV->execute([139, 'SKU-00139', 3050, 2745]);
$stmtI->execute([139, '/uploads/products/Printed (28).jpg']);
$stmtP->execute([140, 5, 'Red Floral Motif Saree', 'A rich red saree with a delicate all-over floral motif and a heavy, ornate border, perfect for weddings and formal gatherings.']);
$stmtV->execute([140, 'SKU-00140', 3050, 2745]);
$stmtI->execute([140, '/uploads/products/Printed (29).jpg']);
$stmtP->execute([141, 5, 'Red Geometric Printed Saree', 'A rich red saree with a geometric bandhani print and a heavy, ornate circle pattern on the pallu, perfect for weddings and formal gatherings.']);
$stmtV->execute([141, 'SKU-00141', 3050, 2745]);
$stmtI->execute([141, '/uploads/products/Printed (30).jpg']);
$stmtP->execute([142, 5, 'Red Floral Bandhani Saree', 'A red saree with a traditional floral bandhani print, featuring a detailed border and a unique floral design on the pallu, suitable for traditional events.']);
$stmtV->execute([142, 'SKU-00142', 3050, 2745]);
$stmtI->execute([142, '/uploads/products/Printed (31).jpg']);
$stmtP->execute([143, 5, 'Purple Geometric and Floral Saree', 'A vibrant purple saree with a detailed geometric and floral print, featuring a striking floral border, ideal for festive events and celebrations.']);
$stmtV->execute([143, 'SKU-00143', 3050, 2745]);
$stmtI->execute([143, '/uploads/products/Printed (32).jpg']);
$stmtP->execute([144, 5, 'Magenta Floral Bandhani Saree', 'A magenta saree with a traditional floral bandhani print, featuring a detailed border and a unique floral design on the pallu, suitable for traditional events.']);
$stmtV->execute([144, 'SKU-00144', 3050, 2745]);
$stmtI->execute([144, '/uploads/products/Printed (33).jpg']);
$stmtP->execute([145, 5, 'Orange Elephant and Circle Print Saree', 'A stunning orange saree with a detailed elephant and geometric pattern on the pallu and an intricate circle design on the body, perfect for special occasions.']);
$stmtV->execute([145, 'SKU-00145', 3050, 2745]);
$stmtI->execute([145, '/uploads/products/Printed (34).jpg']);
$stmtP->execute([146, 5, 'Yellow Elephant and Geometric Print Saree', 'A stunning yellow saree with a detailed elephant and geometric pattern on the pallu and an intricate circle design on the body, perfect for special occasions.']);
$stmtV->execute([146, 'SKU-00146', 3050, 2745]);
$stmtI->execute([146, '/uploads/products/Printed (35).jpg']);
$stmtP->execute([147, 5, 'Red Bird and Geometric Print Saree', 'A vibrant red saree featuring a unique checked and bird pattern on the pallu and a delicate geometric print on the body, perfect for special occasions.']);
$stmtV->execute([147, 'SKU-00147', 3050, 2745]);
$stmtI->execute([147, '/uploads/products/Printed (36).jpg']);
$stmtP->execute([148, 5, 'Purple Geometric and Striped Saree', 'A rich purple saree featuring a bold geometric and striped design on the pallu and an intricate check pattern on the body, perfect for a traditional and stylish look.']);
$stmtV->execute([148, 'SKU-00148', 3050, 2745]);
$stmtI->execute([148, '/uploads/products/Printed (37).jpg']);
$stmtP->execute([149, 5, 'Pink Geometric Bandhani Saree', 'A stunning pink saree with a geometric bandhani print and a heavy, ornate circle and mirror work border, perfect for weddings and formal gatherings.']);
$stmtV->execute([149, 'SKU-00149', 3050, 2745]);
$stmtI->execute([149, '/uploads/products/Printed (38).jpg']);
$stmtP->execute([150, 5, 'Purple Geometric Bandhani Saree', 'A stunning purple saree with a geometric bandhani print and a heavy, ornate circle and mirror work border, perfect for weddings and formal gatherings.']);
$stmtV->execute([150, 'SKU-00150', 3050, 2745]);
$stmtI->execute([150, '/uploads/products/Printed (39).jpg']);
$stmtP->execute([151, 5, 'Orange Geometric Bandhani Saree', 'A stunning orange saree with a geometric bandhani print and a heavy, ornate circle and mirror work border, perfect for weddings and formal gatherings.']);
$stmtV->execute([151, 'SKU-00151', 3050, 2745]);
$stmtI->execute([151, '/uploads/products/Printed (40).jpg']);
$stmtP->execute([152, 5, 'Purple Elephant and Geometric Print Saree', 'A stunning purple saree with a detailed elephant and geometric pattern on the pallu and an intricate circle design on the body, perfect for special occasions.']);
$stmtV->execute([152, 'SKU-00152', 3050, 2745]);
$stmtI->execute([152, '/uploads/products/Printed (41).jpg']);
$stmtP->execute([153, 5, 'Red Geometric Bandhani Saree', 'A stunning red saree with a geometric bandhani print and a heavy, ornate circle and mirror work border, perfect for weddings and formal gatherings.']);
$stmtV->execute([153, 'SKU-00153', 3050, 2745]);
$stmtI->execute([153, '/uploads/products/Printed (42).jpg']);
$stmtP->execute([154, 5, 'Red Wedding Motif Saree', 'A traditional red saree with intricate wedding motifs and a detailed geometric print, featuring a heavy golden border, ideal for bridal wear.']);
$stmtV->execute([154, 'SKU-00154', 3050, 2745]);
$stmtI->execute([154, '/uploads/products/Printed (43).jpg']);
$stmtP->execute([155, 5, 'Yellow Bird and Geometric Print Saree', 'A vibrant yellow saree featuring a unique checked and bird pattern on the pallu and a delicate geometric print on the body, perfect for special occasions.']);
$stmtV->execute([155, 'SKU-00155', 3050, 2745]);
$stmtI->execute([155, '/uploads/products/Printed (44).jpg']);
$stmtP->execute([156, 5, 'Red Elephant and Circle Print Saree', 'A stunning red saree with a detailed elephant and geometric pattern on the pallu and an intricate circle design on the body, perfect for special occasions.']);
$stmtV->execute([156, 'SKU-00156', 3050, 2745]);
$stmtI->execute([156, '/uploads/products/Printed (45).jpg']);
$stmtP->execute([157, 5, 'Lavender Wedding Motif Saree', 'A traditional lavender saree with intricate wedding motifs and a detailed geometric print, featuring a heavy golden border, ideal for bridal wear.']);
$stmtV->execute([157, 'SKU-00157', 3050, 2745]);
$stmtI->execute([157, '/uploads/products/Printed (46).jpg']);
$stmtP->execute([158, 5, 'Green Geometric Bandhani Saree', 'A stunning green saree with a geometric bandhani print and a heavy, ornate circle and mirror work border, perfect for weddings and formal gatherings.']);
$stmtV->execute([158, 'SKU-00158', 3050, 2745]);
$stmtI->execute([158, '/uploads/products/Printed (47).jpg']);
$stmtP->execute([159, 5, 'Maroon Bird and Geometric Print Saree', 'A vibrant maroon saree featuring a unique checked and bird pattern on the pallu and a delicate geometric print on the body, perfect for special occasions.']);
$stmtV->execute([159, 'SKU-00159', 3050, 2745]);
$stmtI->execute([159, '/uploads/products/Printed (48).jpg']);
$stmtP->execute([160, 5, 'Purple Bird and Geometric Print Saree', 'A vibrant purple saree featuring a unique checked and bird pattern on the pallu and a delicate geometric print on the body, perfect for special occasions.']);
$stmtV->execute([160, 'SKU-00160', 3050, 2745]);
$stmtI->execute([160, '/uploads/products/Printed (49).jpg']);
$stmtP->execute([161, 5, 'Green Geometric Bandhani Saree', 'A stunning green saree with a geometric bandhani print and a heavy, ornate circle and mirror work border, perfect for weddings and formal gatherings.']);
$stmtV->execute([161, 'SKU-00161', 3050, 2745]);
$stmtI->execute([161, '/uploads/products/Printed (50).jpg']);
$stmtP->execute([162, 5, 'Maroon Bird and Geometric Print Saree', 'A vibrant maroon saree featuring a unique checked and bird pattern on the pallu and a delicate geometric print on the body, perfect for special occasions.']);
$stmtV->execute([162, 'SKU-00162', 3050, 2745]);
$stmtI->execute([162, '/uploads/products/Printed (51).jpg']);
$stmtP->execute([163, 5, 'Purple Elephant and Circle Print Saree', 'A stunning purple saree with a detailed elephant and geometric pattern on the pallu and an intricate circle design on the body, perfect for special occasions.']);
$stmtV->execute([163, 'SKU-00163', 3050, 2745]);
$stmtI->execute([163, '/uploads/products/Printed (52).jpg']);
$stmtP->execute([164, 5, 'Dark Purple Geometric Bandhani Saree', 'A stunning dark purple saree with a geometric bandhani print and a heavy, ornate circle and mirror work border, perfect for weddings and formal gatherings.']);
$stmtV->execute([164, 'SKU-00164', 3050, 2745]);
$stmtI->execute([164, '/uploads/products/Printed (53).jpg']);
$stmtP->execute([165, 5, 'Purple Wedding Motif Saree', 'A traditional purple saree with intricate wedding motifs and a detailed geometric print, featuring a heavy golden border, ideal for bridal wear.']);
$stmtV->execute([165, 'SKU-00165', 3050, 2745]);
$stmtI->execute([165, '/uploads/products/Printed (54).jpg']);
$stmtP->execute([166, 5, 'Yellow Geometric Bandhani Saree', 'A stunning yellow saree with a geometric bandhani print and a heavy, ornate circle and mirror work border, perfect for weddings and formal gatherings.']);
$stmtV->execute([166, 'SKU-00166', 3050, 2745]);
$stmtI->execute([166, '/uploads/products/Printed (55).jpg']);
$stmtP->execute([167, 5, 'Lavender Wedding Motif Saree', 'A traditional lavender saree with intricate wedding motifs and a detailed geometric print, featuring a heavy golden border, ideal for bridal wear.']);
$stmtV->execute([167, 'SKU-00167', 3050, 2745]);
$stmtI->execute([167, '/uploads/products/Printed (56).jpg']);
$stmtP->execute([168, 6, 'Pyor Gotta Patti Saree', 'A stunning saree featuring intricate Gota Patti work on a silk fabric. The saree has a beautiful border with floral motifs and a delicate single flower on the pallu.']);
$stmtV->execute([168, 'SKU-00168', 2950, 2655]);
$stmtI->execute([168, '/uploads/products/Pyor Gotta Patti (1).jpg']);
$stmtP->execute([169, 6, 'Pyor Gotta Patti Saree', 'A stunning magenta saree featuring intricate Gota Patti work on a silk fabric. The saree has a beautiful border with a zigzag pattern and scattered star motifs on the body.']);
$stmtV->execute([169, 'SKU-00169', 2950, 2655]);
$stmtI->execute([169, '/uploads/products/Pyor Gotta Patti (2).jpg']);
$stmtP->execute([170, 6, 'Pyor Gotta Patti Saree', 'A stunning rust-colored saree with fine silver Gota Patti work. The saree has a unique geometric and floral border and delicate scattered motifs on the body.']);
$stmtV->execute([170, 'SKU-00170', 3200, 2880]);
$stmtI->execute([170, '/uploads/products/Pyor Gotta Patti (3).jpg']);
$stmtP->execute([171, 6, 'Pyor Gotta Patti Saree', 'A stunning dusty rose saree featuring intricate Gota Patti work on a pure silk fabric. The saree has a beautiful border with floral and leaf motifs and delicate leaf motifs scattered on the body.']);
$stmtV->execute([171, 'SKU-00171', 3150, 2835]);
$stmtI->execute([171, '/uploads/products/Pyor Gotta Patti (4).jpg']);
$stmtP->execute([172, 6, 'Pyor Gotta Patti Saree', 'A gorgeous pink saree with golden Gota Patti work. The border features a beautiful floral pattern, complemented by small floral motifs scattered across the fabric.']);
$stmtV->execute([172, 'SKU-00172', 2950, 2655]);
$stmtI->execute([172, '/uploads/products/Pyor Gotta Patti (5).jpg']);
$stmtP->execute([173, 6, 'Pyor Gotta Patti Saree', 'An elegant dark green saree with Gota Patti work. The border showcases a delicate floral design, and the body is adorned with small scattered star motifs.']);
$stmtV->execute([173, 'SKU-00173', 2950, 2655]);
$stmtI->execute([173, '/uploads/products/Pyor Gotta Patti (6).jpg']);
$stmtP->execute([174, 6, 'Pyor Gotta Patti Saree', 'A lovely olive green saree with intricate Gota Patti work. The saree has a classic floral and zigzag border, with tiny star motifs scattered on the body.']);
$stmtV->execute([174, 'SKU-00174', 2950, 2655]);
$stmtI->execute([174, '/uploads/products/Pyor Gotta Patti (7).jpg']);
$stmtP->execute([175, 6, 'Pyor Gotta Patti Saree', 'A beautiful purple saree with fine Gota Patti work. The saree features a border with zigzag and floral patterns, with small star motifs scattered throughout the fabric.']);
$stmtV->execute([175, 'SKU-00175', 2950, 2655]);
$stmtI->execute([175, '/uploads/products/Pyor Gotta Patti (8).jpg']);
$stmtP->execute([176, 6, 'Pyor Gotta Patti Saree', 'A stunning red saree with classic Gota Patti work. The saree features a zigzag and floral patterned border and is decorated with small, scattered star motifs.']);
$stmtV->execute([176, 'SKU-00176', 3150, 2835]);
$stmtI->execute([176, '/uploads/products/Pyor Gotta Patti (9).jpg']);
$stmtP->execute([177, 6, 'Pyor Gotta Patti Saree', 'A radiant fuchsia saree featuring delicate Gota Patti work on pure silk. The border has a mix of zigzag and floral patterns, with small flower motifs scattered across the body.']);
$stmtV->execute([177, 'SKU-00177', 3150, 2835]);
$stmtI->execute([177, '/uploads/products/Pyor Gotta Patti (10).jpg']);
$stmtP->execute([178, 6, 'Pyor Gotta Patti Saree', 'A striking magenta saree adorned with intricate silver Gota Patti work. The border showcases a charming combination of floral and zigzag designs, with small floral motifs scattered on the body.']);
$stmtV->execute([178, 'SKU-00178', 2950, 2655]);
$stmtI->execute([178, '/uploads/products/Pyor Gotta Patti (11).jpg']);
$stmtP->execute([179, 6, 'Pyor Gotta Patti Saree', 'An elegant purple saree with fine golden Gota Patti work. The border features a zigzag and floral pattern, with delicate leaf motifs scattered throughout the fabric.']);
$stmtV->execute([179, 'SKU-00179', 2950, 2655]);
$stmtI->execute([179, '/uploads/products/Pyor Gotta Patti (12).jpg']);
$stmtP->execute([180, 6, 'Pyor Gotta Patti Saree', 'A gorgeous blue-green saree with heavy Gota Patti work. The border is designed with large spiral and zigzag patterns, with small floral motifs scattered on the brocade fabric.']);
$stmtV->execute([180, 'SKU-00180', 3800, 3420]);
$stmtI->execute([180, '/uploads/products/Pyor Gotta Patti (13).jpg']);
$stmtP->execute([181, 6, 'Pyor Gotta Patti Saree', 'A sophisticated beige saree with Gota Patti work on a brocade pattern. The saree has a stunning border with floral and zigzag motifs, with scattered floral designs on the body.']);
$stmtV->execute([181, 'SKU-00181', 3200, 2880]);
$stmtI->execute([181, '/uploads/products/Pyor Gotta Patti (14).jpg']);
$stmtP->execute([182, 6, 'Pyor Gotta Patti Saree', 'A beautiful pista green saree with intricate Gota Patti work on a brocade pattern. The border features a zigzag pattern with floral motifs, with scattered star motifs on the body.']);
$stmtV->execute([182, 'SKU-00182', 2950, 2655]);
$stmtI->execute([182, '/uploads/products/Pyor Gotta Patti (15).jpg']);
$stmtP->execute([183, 6, 'Pyor Gotta Patti Saree', 'A stunning pista green saree with Gota Patti work on a brocade pattern. The saree has a bold Gota Patti border with unique floral motifs and scattered leaf designs on the body.']);
$stmtV->execute([183, 'SKU-00183', 3200, 2880]);
$stmtI->execute([183, '/uploads/products/Pyor Gotta Patti (16).jpg']);
$stmtP->execute([184, 6, 'Pyor Gotta Patti Saree', 'An elegant pink saree with intricate Gota Patti work on a brocade pattern. The saree features a detailed floral and zigzag border with beautiful square floral patterns and scattered motifs on the body.']);
$stmtV->execute([184, 'SKU-00184', 3500, 3150]);
$stmtI->execute([184, '/uploads/products/Pyor Gotta Patti (17).jpg']);
$stmtP->execute([185, 6, 'Pyor Gotta Patti Saree', 'A sophisticated dusty grey saree featuring intricate Gota Patti work on a brocade pattern. The border has a scalloped floral design, with small floral motifs scattered throughout the fabric.']);
$stmtV->execute([185, 'SKU-00185', 3200, 2880]);
$stmtI->execute([185, '/uploads/products/Pyor Gotta Patti (18).jpg']);
$stmtP->execute([186, 6, 'Pyor Gotta Patti Saree', 'A beautiful pista green saree featuring intricate Gota Patti work on a brocade pattern. The border is a unique zigzag and floral design, with delicate motifs scattered on the body.']);
$stmtV->execute([186, 'SKU-00186', 3200, 2880]);
$stmtI->execute([186, '/uploads/products/Pyor Gotta Patti (19).jpg']);
$stmtP->execute([187, 6, 'Pyor Gotta Patti Saree', 'A graceful dusty pink saree with fine Gota Patti work on a brocade pattern. The border showcases an elegant scroll and floral design with scattered small motifs on the body.']);
$stmtV->execute([187, 'SKU-00187', 3200, 2880]);
$stmtI->execute([187, '/uploads/products/Pyor Gotta Patti (20).jpg']);
$stmtP->execute([188, 6, 'Pyor Gotta Patti Saree', 'A luxurious wine-colored saree with rich Gota Patti work. The border features a bold scalloped design with leaf motifs, and the body has a delicate star motif.']);
$stmtV->execute([188, 'SKU-00188', 3950, 3555]);
$stmtI->execute([188, '/uploads/products/Pyor Gotta Patti (21).jpg']);
$stmtP->execute([189, 6, 'Pyor Gotta Patti Saree', 'A beautiful deep plum saree featuring intricate Gota Patti work and pearl detailing. The border has a detailed leaf pattern with a bold floral motif on the body.']);
$stmtV->execute([189, 'SKU-00189', 3950, 3555]);
$stmtI->execute([189, '/uploads/products/Pyor Gotta Patti (22).jpg']);
$stmtP->execute([190, 6, 'Pyor Gotta Patti Saree', 'A rich maroon saree with a combination of golden and silver Gota Patti work. The border features a detailed floral pattern, with bold floral motifs on the body.']);
$stmtV->execute([190, 'SKU-00190', 4000, 3600]);
$stmtI->execute([190, '/uploads/products/Pyor Gotta Patti (23).jpg']);
$stmtP->execute([191, 6, 'Pyor Gotta Patti Saree', 'A striking deep maroon saree with dense golden Gota Patti work. The saree features a heavy border with floral motifs and a single large floral motif on the pallu.']);
$stmtV->execute([191, 'SKU-00191', 3950, 3555]);
$stmtI->execute([191, '/uploads/products/Pyor Gotta Patti (24).jpg']);
$stmtP->execute([192, 6, 'Pyor Gotta Patti Saree', 'An elegant plum saree with detailed Gota Patti work. The border is a bold and dense floral pattern, with a large circular floral motif on the pallu.']);
$stmtV->execute([192, 'SKU-00192', 3600, 3240]);
$stmtI->execute([192, '/uploads/products/Pyor Gotta Patti (25).jpg']);
$stmtP->execute([193, 6, 'Pyor Gotta Patti Saree', 'A stunning brown saree featuring intricate Gota Patti work. The border combines geometric and floral patterns, with a detailed floral design on the pallu and scattered motifs on the body.']);
$stmtV->execute([193, 'SKU-00193', 3800, 3420]);
$stmtI->execute([193, '/uploads/products/Pyor Gotta Patti (26).jpg']);
$stmtP->execute([194, 6, 'Pyor Gotta Patti Saree', 'A beautiful mauve saree featuring intricate Gota Patti work. The border showcases a detailed peacock and floral design, with a single leaf motif on the body.']);
$stmtV->execute([194, 'SKU-00194', 3800, 3420]);
$stmtI->execute([194, '/uploads/products/Pyor Gotta Patti (27).jpg']);
$stmtP->execute([195, 6, 'Pyor Gotta Patti Saree', 'A luxurious deep green saree with Gota Patti and stone work. The border has a detailed leaf pattern with a bold floral motif and a center stone on the body.']);
$stmtV->execute([195, 'SKU-00195', 3400, 3060]);
$stmtI->execute([195, '/uploads/products/Pyor Gotta Patti (28).jpg']);
$stmtP->execute([196, 6, 'Pyor Gotta Patti Saree', 'A deep purple saree with intricate Gota Patti work and sequin details. The border features a geometric pattern, with a delicate floral motif on the body.']);
$stmtV->execute([196, 'SKU-00196', 3600, 3240]);
$stmtI->execute([196, '/uploads/products/Pyor Gotta Patti (29).jpg']);
$stmtP->execute([197, 6, 'Pyor Gotta Patti Saree', 'An elegant magenta saree with a classic Gota Patti border. The saree is adorned with intricate floral and leaf motifs and has a large circular floral motif on the body.']);
$stmtV->execute([197, 'SKU-00197', 3600, 3240]);
$stmtI->execute([197, '/uploads/products/Pyor Gotta Patti (30).jpg']);
$stmtP->execute([198, 6, 'Pyor Gotta Patti Saree', 'A festive red saree with intricate Gota Patti work. The border features a scalloped leaf pattern, and the body has a large circular motif with delicate flowers and connecting lines.']);
$stmtV->execute([198, 'SKU-00198', 3400, 3060]);
$stmtI->execute([198, '/uploads/products/Pyor Gotta Patti (31).jpg']);
$stmtP->execute([199, 6, 'Pyor Gotta Patti Saree', 'A rich plum saree with heavy Gota Patti work. The scalloped border features bold leaf motifs with a stunning star motif on the body of the saree.']);
$stmtV->execute([199, 'SKU-00199', 3800, 3420]);
$stmtI->execute([199, '/uploads/products/Pyor Gotta Patti (32).jpg']);
$stmtP->execute([200, 6, 'Pyor Gotta Patti Saree', 'A vibrant yellow saree with heavy silver Gota Patti work. The border features a dense floral and geometric pattern, with scattered leaf and floral motifs on the body.']);
$stmtV->execute([200, 'SKU-00200', 3600, 3240]);
$stmtI->execute([200, '/uploads/products/Pyor Gotta Patti (33).jpg']);
$stmtP->execute([201, 6, 'Pyor Gotta Patti Saree', 'A stunning white saree with elaborate Gota Patti and mirror work. The border features a dense floral design with intricate patterns on the pallu and a contrasting red piping.']);
$stmtV->execute([201, 'SKU-00201', 3700, 3330]);
$stmtI->execute([201, '/uploads/products/Pyor Gotta Patti (34).jpg']);
$stmtP->execute([202, 6, 'Pyor Gotta Patti Saree', 'A beautiful dark green saree with delicate Gota Patti work. The saree has a stunning border with floral motifs and is decorated with small scattered flowers on the body.']);
$stmtV->execute([202, 'SKU-00202', 3150, 2835]);
$stmtI->execute([202, '/uploads/products/Pyor Gotta Patti (35).jpg']);
$stmtP->execute([203, 6, 'Pyor Gotta Patti Saree', 'A charming pink saree with golden Gota Patti work. The saree features a border with zigzag and floral motifs and is decorated with small scattered floral motifs on the body.']);
$stmtV->execute([203, 'SKU-00203', 3150, 2835]);
$stmtI->execute([203, '/uploads/products/Pyor Gotta Patti (36).jpg']);
$stmtP->execute([204, 6, 'Pyor Gotta Patti Saree', 'A lovely rose pink saree with Gota Patti work. The border features a zigzag and floral design with small floral motifs scattered throughout the fabric.']);
$stmtV->execute([204, 'SKU-00204', 3150, 2835]);
$stmtI->execute([204, '/uploads/products/Pyor Gotta Patti (37).jpg']);
$stmtP->execute([205, 6, 'Pyor Gotta Patti Saree', 'A graceful mauve saree with golden Gota Patti work. The border showcases a zigzag and floral design, with small floral motifs scattered on the body.']);
$stmtV->execute([205, 'SKU-00205', 3150, 2835]);
$stmtI->execute([205, '/uploads/products/Pyor Gotta Patti (38).jpg']);
$stmtP->execute([206, 6, 'Pyor Gotta Patti Saree', 'A gorgeous magenta saree with golden Gota Patti work. The border features a detailed floral and zigzag pattern, with small scattered motifs on the body.']);
$stmtV->execute([206, 'SKU-00206', 3150, 2835]);
$stmtI->execute([206, '/uploads/products/Pyor Gotta Patti (39).jpg']);
$stmtP->execute([207, 6, 'Pyor Gotta Patti Saree', 'A beautiful pista green saree with Gota Patti work. The border features a zigzag pattern with floral motifs and is decorated with small scattered flowers on the body.']);
$stmtV->execute([207, 'SKU-00207', 3150, 2835]);
$stmtI->execute([207, '/uploads/products/Pyor Gotta Patti (40).jpg']);
$stmtP->execute([208, 6, 'Pyor Gotta Patti Saree', 'A classic red saree with a heavy Gota Patti border. The border features a dense floral pattern with leaf motifs and a detailed floral design on the body of the saree.']);
$stmtV->execute([208, 'SKU-00208', 3400, 3060]);
$stmtI->execute([208, '/uploads/products/Pyor Gotta Patti (41).jpg']);
$stmtP->execute([209, 6, 'Pyor Gotta Patti Saree', 'A stunning olive-green saree with intricate Gota Patti work. The saree features a border with elegant circular and floral motifs and delicate leaf designs on the body.']);
$stmtV->execute([209, 'SKU-00209', 3900, 3510]);
$stmtI->execute([209, '/uploads/products/Pyor Gotta Patti (42).jpg']);
$stmtP->execute([210, 6, 'Pyor Gotta Patti Saree', 'A beautiful pista green saree with silver Gota Patti work. The border showcases a detailed pattern of circular floral motifs, with scattered leaf designs on the body.']);
$stmtV->execute([210, 'SKU-00210', 3900, 3510]);
$stmtI->execute([210, '/uploads/products/Pyor Gotta Patti (43).jpg']);
$stmtP->execute([211, 6, 'Pyor Gotta Patti Saree', 'An elegant lavender saree with heavy golden Gota Patti and mirror work. The saree features a scalloped border with intricate floral and mirror work, and a delicate floral brocade pattern.']);
$stmtV->execute([211, 'SKU-00211', 3700, 3330]);
$stmtI->execute([211, '/uploads/products/Pyor Gotta Patti (44).jpg']);
$stmtP->execute([212, 6, 'Pyor Gotta Patti Saree', 'A beautiful mauve saree with intricate Gota Patti work. The border is adorned with a zigzag and leaf pattern, with a large leaf motif on the pallu.']);
$stmtV->execute([212, 'SKU-00212', 3200, 2880]);
$stmtI->execute([212, '/uploads/products/Pyor Gotta Patti (45).jpg']);
$stmtP->execute([213, 6, 'Pyor Gotta Patti Saree', 'A sophisticated dusty pink saree with detailed Gota Patti and mirror work. The border features a scalloped design with floral and leaf motifs, with a subtle brocade pattern on the fabric.']);
$stmtV->execute([213, 'SKU-00213', 3200, 2880]);
$stmtI->execute([213, '/uploads/products/Pyor Gotta Patti (46).jpg']);
$stmtP->execute([214, 6, 'Pyor Gotta Patti Saree', 'A stunning magenta saree with Gota Patti and mirror work. The border has a graceful zigzag and leaf pattern, with a bold floral motif on the pallu.']);
$stmtV->execute([214, 'SKU-00214', 3200, 2880]);
$stmtI->execute([214, '/uploads/products/Pyor Gotta Patti (47).jpg']);
$stmtP->execute([215, 6, 'Pyor Gotta Patti Saree', 'A classic royal blue saree with intricate Gota Patti work. The border is a bold combination of geometric and floral motifs, with stunning floral designs scattered on the body.']);
$stmtV->execute([215, 'SKU-00215', 3500, 3150]);
$stmtI->execute([215, '/uploads/products/Pyor Gotta Patti (48).jpg']);
$stmtP->execute([216, 6, 'Pyor Gotta Patti Saree', 'A stunning beige saree with intricate Gota Patti and mirror work. The saree features a broad border with floral and mirror motifs, with a small check pattern on the fabric.']);
$stmtV->execute([216, 'SKU-00216', 3200, 2880]);
$stmtI->execute([216, '/uploads/products/Pyor Gotta Patti (49).jpg']);
$stmtP->execute([217, 6, 'Pyor Gotta Patti Saree', 'An elegant off-white saree with delicate golden Gota Patti work. The border has a beautiful scalloped floral design with sequins, and the body has a subtle check pattern with scattered motifs.']);
$stmtV->execute([217, 'SKU-00217', 3200, 2880]);
$stmtI->execute([217, '/uploads/products/Pyor Gotta Patti (50).jpg']);
$stmtP->execute([218, 6, 'Pyor Gotta Patti Saree', 'An elegant off-white saree with delicate golden Gota Patti work. The saree features a broad scalloped border with floral motifs and subtle scattered patterns on the body.']);
$stmtV->execute([218, 'SKU-00218', 3100, 2790]);
$stmtI->execute([218, '/uploads/products/Pyor Gotta Patti (51).jpg']);
$stmtP->execute([219, 6, 'Pyor Gotta Patti Saree', 'A beautiful dusty rose saree with intricate Gota Patti work on a brocade pattern. The saree has a heavy scalloped border with floral motifs and a delicate brocade pattern on the fabric.']);
$stmtV->execute([219, 'SKU-00219', 3100, 2790]);
$stmtI->execute([219, '/uploads/products/Pyor Gotta Patti (52).jpg']);
$stmtP->execute([220, 6, 'Pyor Gotta Patti Saree', 'A beautiful dusty pink saree with intricate Gota Patti work. The saree has a stunning border with a combination of leaf and floral patterns, with a brocade pattern on the fabric.']);
$stmtV->execute([220, 'SKU-00220', 3100, 2790]);
$stmtI->execute([220, '/uploads/products/Pyor Gotta Patti (53).jpg']);
$stmtP->execute([221, 6, 'Pyor Gotta Patti Saree', 'An elegant peach-colored saree with fine Gota Patti work. The border features a unique floral and zigzag pattern with scattered small floral motifs on the body.']);
$stmtV->execute([221, 'SKU-00221', 3100, 2790]);
$stmtI->execute([221, '/uploads/products/Pyor Gotta Patti (54).jpg']);
$stmtP->execute([222, 6, 'Pyor Gotta Patti Saree', 'An elegant pink saree with intricate Gota Patti work on a brocade pattern. The saree has a stunning scalloped border with floral motifs and scattered patterns on the body.']);
$stmtV->execute([222, 'SKU-00222', 3100, 2790]);
$stmtI->execute([222, '/uploads/products/Pyor Gotta Patti (55).jpg']);
$stmtP->execute([223, 6, 'Pyor Gotta Patti Saree', 'A beautiful dusty grey saree with Gota Patti and mirror work. The border features a combination of floral and mirror patterns, with large floral motifs on the body.']);
$stmtV->execute([223, 'SKU-00223', 3700, 3330]);
$stmtI->execute([223, '/uploads/products/pyor Gotta Patti (56).jpg']);
$stmtP->execute([224, 6, 'Pyor Gotta Patti Saree', 'A gorgeous plum saree with intricate Gota Patti and mirror work. The saree features a scalloped border with intricate floral and mirror work, with a brocade pattern on the fabric.']);
$stmtV->execute([224, 'SKU-00224', 39500, 35550]);
$stmtI->execute([224, '/uploads/products/Pyor Gotta Patti (57).jpg']);
$stmtP->execute([225, 6, 'Pyor Gotta Patti Saree', 'A stunning red saree with a heavy golden Gota Patti border. The saree has a broad scalloped border with leaf motifs and scattered star patterns on the body.']);
$stmtV->execute([225, 'SKU-00225', 3200, 2880]);
$stmtI->execute([225, '/uploads/products/Pyor Gotta Patti (58).jpg']);
$pdo->exec('SET FOREIGN_KEY_CHECKS = 1;');
echo 'SUCCESS';
